// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module merge_sort_parallel_merge_arrays_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        in_r_address1,
        in_r_ce1,
        in_r_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [23:0] in_r_address0;
output   in_r_ce0;
input  [31:0] in_r_q0;
output  [23:0] in_r_address1;
output   in_r_ce1;
input  [31:0] in_r_q1;
output  [23:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;

reg ap_idle;
reg in_r_ce0;
reg in_r_ce1;
reg[23:0] out_r_address0;
reg out_r_ce0;
reg out_r_we0;
reg[31:0] out_r_d0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_159_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] i3_8_reg_376;
reg    ap_block_pp0_stage0_11001;
reg   [23:0] i_2_reg_384;
reg   [31:0] f2_8_reg_389;
reg   [31:0] f1_10_reg_395;
reg   [0:0] icmp_ln47_reg_402;
wire   [0:0] icmp_ln50_fu_176_p2;
reg   [0:0] icmp_ln50_reg_411;
reg   [31:0] ap_phi_mux_f2_1_phi_fu_107_p4;
wire   [31:0] ap_phi_reg_pp0_iter1_f2_1_reg_104;
wire   [0:0] and_ln51_fu_217_p2;
wire   [31:0] f2_fu_223_p2;
reg   [31:0] ap_phi_mux_f1_1_phi_fu_116_p4;
wire   [31:0] f1_fu_229_p2;
wire   [31:0] ap_phi_reg_pp0_iter1_f1_1_reg_113;
wire   [63:0] zext_ln49_fu_171_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln50_fu_182_p1;
wire   [63:0] zext_ln47_fu_195_p1;
wire   [23:0] out_addr_gep_fu_95_p3;
reg   [31:0] i2_fu_36;
wire   [31:0] i2_12_fu_306_p3;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
reg   [31:0] ap_sig_allocacmp_i2_9;
reg   [31:0] f1_9_fu_40;
wire   [31:0] i3_7_fu_314_p3;
reg   [31:0] ap_sig_allocacmp_i3_8;
reg   [23:0] i_fu_44;
wire   [23:0] add_ln47_fu_165_p2;
reg   [23:0] ap_sig_allocacmp_i_2;
reg   [31:0] f2_01_fu_48;
wire   [31:0] f2_10_fu_291_p3;
reg   [31:0] ap_sig_allocacmp_f2_8;
reg   [31:0] f1_02_fu_52;
wire   [31:0] f1_12_fu_299_p3;
reg   [31:0] ap_sig_allocacmp_f1_10;
wire   [0:0] icmp_ln51_2_fu_205_p2;
wire   [0:0] icmp_ln51_fu_200_p2;
wire   [0:0] xor_ln51_fu_211_p2;
wire   [0:0] icmp_ln60_fu_235_p2;
wire   [0:0] icmp_ln60_2_fu_241_p2;
wire   [31:0] i2_10_fu_252_p2;
wire   [0:0] icmp_ln64_fu_263_p2;
wire   [31:0] i3_fu_258_p2;
wire   [0:0] icmp_ln66_fu_277_p2;
wire   [0:0] and_ln60_fu_246_p2;
wire   [31:0] i2_13_fu_269_p3;
wire   [31:0] i3_6_fu_283_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_101;
reg    ap_condition_156;
reg    ap_condition_115;
reg    ap_condition_109;
reg    ap_condition_131;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

merge_sort_parallel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            f1_02_fu_52 <= 32'd0;
        end else if (((icmp_ln47_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            f1_02_fu_52 <= f1_12_fu_299_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            f1_9_fu_40 <= 32'd256;
        end else if (((icmp_ln47_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            f1_9_fu_40 <= i3_7_fu_314_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            f2_01_fu_48 <= 32'd128;
        end else if (((icmp_ln47_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            f2_01_fu_48 <= f2_10_fu_291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_101)) begin
        if ((icmp_ln47_reg_402 == 1'd0)) begin
            i2_fu_36 <= i2_12_fu_306_p3;
        end else if ((ap_loop_init_pp0_iter1_reg == 1'b1)) begin
            i2_fu_36 <= 32'd128;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_156)) begin
        if ((icmp_ln47_fu_159_p2 == 1'd0)) begin
            i_fu_44 <= add_ln47_fu_165_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 24'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        f1_10_reg_395 <= ap_sig_allocacmp_f1_10;
        f2_8_reg_389 <= ap_sig_allocacmp_f2_8;
        i3_8_reg_376 <= ap_sig_allocacmp_i3_8;
        i_2_reg_384 <= ap_sig_allocacmp_i_2;
        icmp_ln47_reg_402 <= icmp_ln47_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_fu_159_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln50_reg_411 <= icmp_ln50_fu_176_p2;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_159_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_reg_411 == 1'd0) & (1'd0 == and_ln51_fu_217_p2) & (icmp_ln47_reg_402 == 1'd0))) begin
        ap_phi_mux_f1_1_phi_fu_116_p4 = f1_10_reg_395;
    end else if ((((icmp_ln50_reg_411 == 1'd1) & (icmp_ln47_reg_402 == 1'd0)) | ((icmp_ln47_reg_402 == 1'd0) & (1'd1 == and_ln51_fu_217_p2)))) begin
        ap_phi_mux_f1_1_phi_fu_116_p4 = f1_fu_229_p2;
    end else begin
        ap_phi_mux_f1_1_phi_fu_116_p4 = ap_phi_reg_pp0_iter1_f1_1_reg_113;
    end
end

always @ (*) begin
    if (((icmp_ln50_reg_411 == 1'd0) & (1'd0 == and_ln51_fu_217_p2) & (icmp_ln47_reg_402 == 1'd0))) begin
        ap_phi_mux_f2_1_phi_fu_107_p4 = f2_fu_223_p2;
    end else if ((((icmp_ln50_reg_411 == 1'd1) & (icmp_ln47_reg_402 == 1'd0)) | ((icmp_ln47_reg_402 == 1'd0) & (1'd1 == and_ln51_fu_217_p2)))) begin
        ap_phi_mux_f2_1_phi_fu_107_p4 = f2_8_reg_389;
    end else begin
        ap_phi_mux_f2_1_phi_fu_107_p4 = ap_phi_reg_pp0_iter1_f2_1_reg_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            ap_sig_allocacmp_f1_10 = 32'd0;
        end else if (((icmp_ln47_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ap_sig_allocacmp_f1_10 = f1_12_fu_299_p3;
        end else begin
            ap_sig_allocacmp_f1_10 = f1_02_fu_52;
        end
    end else begin
        ap_sig_allocacmp_f1_10 = f1_02_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            ap_sig_allocacmp_f2_8 = 32'd128;
        end else if (((icmp_ln47_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ap_sig_allocacmp_f2_8 = f2_10_fu_291_p3;
        end else begin
            ap_sig_allocacmp_f2_8 = f2_01_fu_48;
        end
    end else begin
        ap_sig_allocacmp_f2_8 = f2_01_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_sig_allocacmp_i2_9 = 32'd128;
    end else begin
        ap_sig_allocacmp_i2_9 = i2_fu_36;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            ap_sig_allocacmp_i3_8 = 32'd256;
        end else if (((icmp_ln47_reg_402 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            ap_sig_allocacmp_i3_8 = i3_7_fu_314_p3;
        end else begin
            ap_sig_allocacmp_i3_8 = f1_9_fu_40;
        end
    end else begin
        ap_sig_allocacmp_i3_8 = f1_9_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 24'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_ce0 = 1'b1;
    end else begin
        in_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_r_ce1 = 1'b1;
    end else begin
        in_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_131)) begin
        if ((1'b1 == ap_condition_109)) begin
            out_r_address0 = out_addr_gep_fu_95_p3;
        end else if ((1'b1 == ap_condition_115)) begin
            out_r_address0 = zext_ln47_fu_195_p1;
        end else begin
            out_r_address0 = 'bx;
        end
    end else begin
        out_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln50_reg_411 == 1'd1) & (icmp_ln47_reg_402 == 1'd0)) | ((icmp_ln47_reg_402 == 1'd0) & (1'd1 == and_ln51_fu_217_p2)))) | ((icmp_ln50_reg_411 == 1'd0) & (1'd0 == and_ln51_fu_217_p2) & (icmp_ln47_reg_402 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_131)) begin
        if ((1'b1 == ap_condition_109)) begin
            out_r_d0 = in_r_q1;
        end else if ((1'b1 == ap_condition_115)) begin
            out_r_d0 = in_r_q0;
        end else begin
            out_r_d0 = 'bx;
        end
    end else begin
        out_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln50_reg_411 == 1'd1) & (icmp_ln47_reg_402 == 1'd0)) | ((icmp_ln47_reg_402 == 1'd0) & (1'd1 == and_ln51_fu_217_p2)))) | ((icmp_ln50_reg_411 == 1'd0) & (1'd0 == and_ln51_fu_217_p2) & (icmp_ln47_reg_402 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_fu_165_p2 = (ap_sig_allocacmp_i_2 + 24'd1);

assign and_ln51_fu_217_p2 = (xor_ln51_fu_211_p2 & icmp_ln51_fu_200_p2);

assign and_ln60_fu_246_p2 = (icmp_ln60_fu_235_p2 & icmp_ln60_2_fu_241_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_101 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_109 = (((icmp_ln50_reg_411 == 1'd1) & (icmp_ln47_reg_402 == 1'd0)) | ((icmp_ln47_reg_402 == 1'd0) & (1'd1 == and_ln51_fu_217_p2)));
end

always @ (*) begin
    ap_condition_115 = ((icmp_ln50_reg_411 == 1'd0) & (1'd0 == and_ln51_fu_217_p2) & (icmp_ln47_reg_402 == 1'd0));
end

always @ (*) begin
    ap_condition_131 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_156 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter1_f1_1_reg_113 = 'bx;

assign ap_phi_reg_pp0_iter1_f2_1_reg_104 = 'bx;

assign f1_12_fu_299_p3 = ((and_ln60_fu_246_p2[0:0] == 1'b1) ? i3_8_reg_376 : ap_phi_mux_f1_1_phi_fu_116_p4);

assign f1_fu_229_p2 = (f1_10_reg_395 + 32'd1);

assign f2_10_fu_291_p3 = ((and_ln60_fu_246_p2[0:0] == 1'b1) ? i2_13_fu_269_p3 : ap_phi_mux_f2_1_phi_fu_107_p4);

assign f2_fu_223_p2 = (f2_8_reg_389 + 32'd1);

assign i2_10_fu_252_p2 = (ap_sig_allocacmp_i2_9 + 32'd256);

assign i2_12_fu_306_p3 = ((and_ln60_fu_246_p2[0:0] == 1'b1) ? i2_13_fu_269_p3 : ap_sig_allocacmp_i2_9);

assign i2_13_fu_269_p3 = ((icmp_ln64_fu_263_p2[0:0] == 1'b1) ? i2_10_fu_252_p2 : 32'd10000000);

assign i3_6_fu_283_p3 = ((icmp_ln66_fu_277_p2[0:0] == 1'b1) ? i3_fu_258_p2 : 32'd10000000);

assign i3_7_fu_314_p3 = ((and_ln60_fu_246_p2[0:0] == 1'b1) ? i3_6_fu_283_p3 : i3_8_reg_376);

assign i3_fu_258_p2 = (i3_8_reg_376 + 32'd256);

assign icmp_ln47_fu_159_p2 = ((ap_sig_allocacmp_i_2 == 24'd10000000) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_176_p2 = ((ap_sig_allocacmp_f2_8 == ap_sig_allocacmp_i3_8) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_205_p2 = (($signed(in_r_q0) < $signed(in_r_q1)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_200_p2 = (($signed(f1_10_reg_395) < $signed(ap_sig_allocacmp_i2_9)) ? 1'b1 : 1'b0);

assign icmp_ln60_2_fu_241_p2 = ((ap_phi_mux_f2_1_phi_fu_107_p4 == i3_8_reg_376) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_235_p2 = ((ap_phi_mux_f1_1_phi_fu_116_p4 == ap_sig_allocacmp_i2_9) ? 1'b1 : 1'b0);

assign icmp_ln64_fu_263_p2 = (($signed(i2_10_fu_252_p2) < $signed(32'd10000000)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_277_p2 = (($signed(i3_fu_258_p2) < $signed(32'd10000000)) ? 1'b1 : 1'b0);

assign in_r_address0 = zext_ln50_fu_182_p1;

assign in_r_address1 = zext_ln49_fu_171_p1;

assign out_addr_gep_fu_95_p3 = zext_ln47_fu_195_p1;

assign xor_ln51_fu_211_p2 = (icmp_ln51_2_fu_205_p2 ^ 1'd1);

assign zext_ln47_fu_195_p1 = i_2_reg_384;

assign zext_ln49_fu_171_p1 = ap_sig_allocacmp_f1_10;

assign zext_ln50_fu_182_p1 = ap_sig_allocacmp_f2_8;

endmodule //merge_sort_parallel_merge_arrays_8
