// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module multi_radix_hex_loser_radix_sort_hex_batch_6_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_5_address0,
        input_5_ce0,
        input_5_q0,
        multi_radix_hex_loser_temp0_5_address0,
        multi_radix_hex_loser_temp0_5_ce0,
        multi_radix_hex_loser_temp0_5_we0,
        multi_radix_hex_loser_temp0_5_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [13:0] input_5_address0;
output   input_5_ce0;
input  [31:0] input_5_q0;
output  [13:0] multi_radix_hex_loser_temp0_5_address0;
output   multi_radix_hex_loser_temp0_5_ce0;
output   multi_radix_hex_loser_temp0_5_we0;
output  [31:0] multi_radix_hex_loser_temp0_5_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln27_fu_663_p2;
wire   [2:0] empty_108_fu_816_p1;
reg   [2:0] empty_108_reg_1646;
wire  signed [14:0] grp_fu_970_p2;
reg   [14:0] mul_ln41_reg_1752;
wire    ap_CS_fsm_state8;
wire   [4:0] mul_i_fu_962_p3;
reg   [4:0] mul_i_reg_1757;
wire  signed [14:0] grp_fu_977_p2;
reg   [14:0] mul_ln43_reg_1762;
reg   [14:0] bucket_address0;
reg    bucket_ce0;
reg    bucket_we0;
reg   [31:0] bucket_d0;
wire   [31:0] bucket_q0;
reg    bucket_ce1;
wire   [31:0] bucket_q1;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_done;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_idle;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_ready;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1030_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1030_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1029_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1029_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1028_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1028_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1027_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1027_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1026_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1026_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1025_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1025_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1024_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1024_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1023_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1023_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1022_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1022_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1021_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1021_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1020_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1020_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1019_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1019_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1018_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1018_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1017_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1017_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1016_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1016_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_out_ap_vld;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_done;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_idle;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_ready;
wire   [14:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_address0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_ce0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_we0;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_d0;
wire   [13:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_input_5_address0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_input_5_ce0;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1062_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1062_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1061_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1061_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1060_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1060_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1059_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1059_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1058_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1058_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1057_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1057_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1056_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1056_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1055_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1055_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1054_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1054_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1053_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1053_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1052_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1052_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1051_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1051_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1050_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1050_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1049_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1049_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1048_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1048_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1047_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1047_out_o_ap_vld;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_done;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_idle;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_ready;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1111_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1111_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1110_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1110_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1109_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1109_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1108_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1108_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1107_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1107_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1106_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1106_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1105_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1105_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1104_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1104_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1103_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1103_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1102_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1102_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1101_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1101_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1100_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1100_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1099_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1099_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1098_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1098_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1097_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1097_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1096_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1096_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_486_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_486_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_485_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_485_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_484_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_484_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_483_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_483_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_482_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_482_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_481_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_481_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_480_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_480_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_479_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_479_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_478_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_478_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_477_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_477_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_476_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_476_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_475_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_475_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_474_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_474_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_473_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_473_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_472_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_472_out_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_471_out;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_471_out_ap_vld;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_done;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_idle;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_ready;
wire   [14:0] grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_bucket_address0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_bucket_ce0;
wire   [13:0] grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_address0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_ce0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_we0;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_d0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_done;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_idle;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_ready;
wire   [14:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_address0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_ce0;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_we0;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_d0;
wire   [14:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_address1;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_ce1;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1143_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1143_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1142_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1142_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1141_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1141_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1140_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1140_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1139_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1139_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1138_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1138_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1137_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1137_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1136_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1136_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1135_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1135_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1134_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1134_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1133_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1133_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1132_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1132_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1131_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1131_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1130_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1130_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1129_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1129_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1128_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1128_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_503_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_503_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_502_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_502_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_501_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_501_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_500_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_500_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_499_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_499_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_498_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_498_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_497_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_497_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_496_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_496_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_495_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_495_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_494_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_494_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_493_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_493_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_492_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_492_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_491_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_491_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_490_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_490_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_489_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_489_out_o_ap_vld;
wire   [31:0] grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_488_out_o;
wire    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_488_out_o_ap_vld;
reg    grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start_reg;
reg    ap_block_state1_ignore_call84;
wire    ap_CS_fsm_state2;
reg    grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] bucket_sizes_345_fu_180;
reg   [31:0] bucket_sizes_344_fu_176;
reg   [31:0] bucket_sizes_343_fu_172;
reg   [31:0] bucket_sizes_342_fu_168;
reg   [31:0] bucket_sizes_341_fu_164;
reg   [31:0] bucket_sizes_340_fu_160;
reg   [31:0] bucket_sizes_339_fu_156;
reg   [31:0] bucket_sizes_338_fu_152;
reg   [31:0] bucket_sizes_337_fu_148;
reg   [31:0] bucket_sizes_336_fu_144;
reg   [31:0] bucket_sizes_335_fu_140;
reg   [31:0] bucket_sizes_334_fu_136;
reg   [31:0] bucket_sizes_333_fu_132;
reg   [31:0] bucket_sizes_332_fu_128;
reg   [31:0] bucket_sizes_331_fu_124;
reg   [31:0] bucket_sizes_fu_120;
reg    grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [31:0] bucket_pointer_272_fu_116;
reg   [31:0] bucket_pointer_271_fu_112;
reg   [31:0] bucket_pointer_270_fu_108;
reg   [31:0] bucket_pointer_269_fu_104;
reg   [31:0] bucket_pointer_268_fu_100;
reg   [31:0] bucket_pointer_267_fu_96;
reg   [31:0] bucket_pointer_266_fu_92;
reg   [31:0] bucket_pointer_265_fu_88;
reg   [31:0] bucket_pointer_264_fu_84;
reg   [31:0] bucket_pointer_263_fu_80;
reg   [31:0] bucket_pointer_262_fu_76;
reg   [31:0] bucket_pointer_261_fu_72;
reg   [31:0] bucket_pointer_260_fu_68;
reg   [31:0] bucket_pointer_259_fu_64;
reg   [31:0] bucket_pointer_258_fu_60;
reg   [31:0] bucket_pointer_fu_56;
reg   [3:0] i_fu_48;
wire   [3:0] i_16_fu_669_p2;
reg    ap_block_state1;
reg   [31:0] bucket_num_fu_52;
wire   [31:0] bucket_num_8_fu_806_p2;
wire  signed [14:0] grp_fu_970_p0;
wire   [13:0] grp_fu_970_p1;
wire  signed [14:0] grp_fu_977_p0;
wire   [13:0] grp_fu_977_p1;
reg    grp_fu_970_ce;
wire    ap_CS_fsm_state7;
reg    grp_fu_977_ce;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start_reg = 1'b0;
#0 grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start_reg = 1'b0;
#0 grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start_reg = 1'b0;
#0 grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start_reg = 1'b0;
#0 grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start_reg = 1'b0;
end

multi_radix_hex_loser_radix_sort_hex_batch_6_1_bucket_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 31250 ),
    .AddressWidth( 15 ))
bucket_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bucket_address0),
    .ce0(bucket_ce0),
    .we0(bucket_we0),
    .d0(bucket_d0),
    .q0(bucket_q0),
    .address1(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_address1),
    .ce1(bucket_ce1),
    .q1(bucket_q1)
);

multi_radix_hex_loser_radix_sort_hex_batch_6_1_Pipeline_1 grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start),
    .ap_done(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_done),
    .ap_idle(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_idle),
    .ap_ready(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_ready),
    .bucket_sizes_1030_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1030_out),
    .bucket_sizes_1030_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1030_out_ap_vld),
    .bucket_sizes_1029_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1029_out),
    .bucket_sizes_1029_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1029_out_ap_vld),
    .bucket_sizes_1028_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1028_out),
    .bucket_sizes_1028_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1028_out_ap_vld),
    .bucket_sizes_1027_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1027_out),
    .bucket_sizes_1027_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1027_out_ap_vld),
    .bucket_sizes_1026_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1026_out),
    .bucket_sizes_1026_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1026_out_ap_vld),
    .bucket_sizes_1025_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1025_out),
    .bucket_sizes_1025_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1025_out_ap_vld),
    .bucket_sizes_1024_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1024_out),
    .bucket_sizes_1024_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1024_out_ap_vld),
    .bucket_sizes_1023_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1023_out),
    .bucket_sizes_1023_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1023_out_ap_vld),
    .bucket_sizes_1022_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1022_out),
    .bucket_sizes_1022_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1022_out_ap_vld),
    .bucket_sizes_1021_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1021_out),
    .bucket_sizes_1021_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1021_out_ap_vld),
    .bucket_sizes_1020_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1020_out),
    .bucket_sizes_1020_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1020_out_ap_vld),
    .bucket_sizes_1019_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1019_out),
    .bucket_sizes_1019_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1019_out_ap_vld),
    .bucket_sizes_1018_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1018_out),
    .bucket_sizes_1018_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1018_out_ap_vld),
    .bucket_sizes_1017_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1017_out),
    .bucket_sizes_1017_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1017_out_ap_vld),
    .bucket_sizes_1016_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1016_out),
    .bucket_sizes_1016_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1016_out_ap_vld),
    .bucket_sizes_out(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_out),
    .bucket_sizes_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_out_ap_vld)
);

multi_radix_hex_loser_radix_sort_hex_batch_6_1_Pipeline_initialization grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start),
    .ap_done(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_done),
    .ap_idle(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_idle),
    .ap_ready(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_ready),
    .bucket_sizes_1030_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1030_out),
    .bucket_sizes_1029_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1029_out),
    .bucket_sizes_1028_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1028_out),
    .bucket_sizes_1027_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1027_out),
    .bucket_sizes_1026_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1026_out),
    .bucket_sizes_1025_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1025_out),
    .bucket_sizes_1024_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1024_out),
    .bucket_sizes_1023_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1023_out),
    .bucket_sizes_1022_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1022_out),
    .bucket_sizes_1021_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1021_out),
    .bucket_sizes_1020_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1020_out),
    .bucket_sizes_1019_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1019_out),
    .bucket_sizes_1018_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1018_out),
    .bucket_sizes_1017_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1017_out),
    .bucket_sizes_1016_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_1016_out),
    .bucket_sizes_reload(grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_bucket_sizes_out),
    .bucket_address0(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_address0),
    .bucket_ce0(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_ce0),
    .bucket_we0(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_we0),
    .bucket_d0(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_d0),
    .input_5_address0(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_input_5_address0),
    .input_5_ce0(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_input_5_ce0),
    .input_5_q0(input_5_q0),
    .bucket_sizes_1062_out_i(bucket_sizes_345_fu_180),
    .bucket_sizes_1062_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1062_out_o),
    .bucket_sizes_1062_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1062_out_o_ap_vld),
    .bucket_sizes_1061_out_i(bucket_sizes_344_fu_176),
    .bucket_sizes_1061_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1061_out_o),
    .bucket_sizes_1061_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1061_out_o_ap_vld),
    .bucket_sizes_1060_out_i(bucket_sizes_343_fu_172),
    .bucket_sizes_1060_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1060_out_o),
    .bucket_sizes_1060_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1060_out_o_ap_vld),
    .bucket_sizes_1059_out_i(bucket_sizes_342_fu_168),
    .bucket_sizes_1059_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1059_out_o),
    .bucket_sizes_1059_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1059_out_o_ap_vld),
    .bucket_sizes_1058_out_i(bucket_sizes_341_fu_164),
    .bucket_sizes_1058_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1058_out_o),
    .bucket_sizes_1058_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1058_out_o_ap_vld),
    .bucket_sizes_1057_out_i(bucket_sizes_340_fu_160),
    .bucket_sizes_1057_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1057_out_o),
    .bucket_sizes_1057_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1057_out_o_ap_vld),
    .bucket_sizes_1056_out_i(bucket_sizes_339_fu_156),
    .bucket_sizes_1056_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1056_out_o),
    .bucket_sizes_1056_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1056_out_o_ap_vld),
    .bucket_sizes_1055_out_i(bucket_sizes_338_fu_152),
    .bucket_sizes_1055_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1055_out_o),
    .bucket_sizes_1055_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1055_out_o_ap_vld),
    .bucket_sizes_1054_out_i(bucket_sizes_337_fu_148),
    .bucket_sizes_1054_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1054_out_o),
    .bucket_sizes_1054_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1054_out_o_ap_vld),
    .bucket_sizes_1053_out_i(bucket_sizes_336_fu_144),
    .bucket_sizes_1053_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1053_out_o),
    .bucket_sizes_1053_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1053_out_o_ap_vld),
    .bucket_sizes_1052_out_i(bucket_sizes_335_fu_140),
    .bucket_sizes_1052_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1052_out_o),
    .bucket_sizes_1052_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1052_out_o_ap_vld),
    .bucket_sizes_1051_out_i(bucket_sizes_334_fu_136),
    .bucket_sizes_1051_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1051_out_o),
    .bucket_sizes_1051_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1051_out_o_ap_vld),
    .bucket_sizes_1050_out_i(bucket_sizes_333_fu_132),
    .bucket_sizes_1050_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1050_out_o),
    .bucket_sizes_1050_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1050_out_o_ap_vld),
    .bucket_sizes_1049_out_i(bucket_sizes_332_fu_128),
    .bucket_sizes_1049_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1049_out_o),
    .bucket_sizes_1049_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1049_out_o_ap_vld),
    .bucket_sizes_1048_out_i(bucket_sizes_331_fu_124),
    .bucket_sizes_1048_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1048_out_o),
    .bucket_sizes_1048_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1048_out_o_ap_vld),
    .bucket_sizes_1047_out_i(bucket_sizes_fu_120),
    .bucket_sizes_1047_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1047_out_o),
    .bucket_sizes_1047_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1047_out_o_ap_vld)
);

multi_radix_hex_loser_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start),
    .ap_done(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_done),
    .ap_idle(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_idle),
    .ap_ready(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_ready),
    .bucket_sizes_1095(bucket_sizes_345_fu_180),
    .bucket_sizes_1094(bucket_sizes_344_fu_176),
    .bucket_sizes_1093(bucket_sizes_343_fu_172),
    .bucket_sizes_1092(bucket_sizes_342_fu_168),
    .bucket_sizes_1091(bucket_sizes_341_fu_164),
    .bucket_sizes_1090(bucket_sizes_340_fu_160),
    .bucket_sizes_1089(bucket_sizes_339_fu_156),
    .bucket_sizes_1088(bucket_sizes_338_fu_152),
    .bucket_sizes_1087(bucket_sizes_337_fu_148),
    .bucket_sizes_1086(bucket_sizes_336_fu_144),
    .bucket_sizes_1085(bucket_sizes_335_fu_140),
    .bucket_sizes_1084(bucket_sizes_334_fu_136),
    .bucket_sizes_1083(bucket_sizes_333_fu_132),
    .bucket_sizes_1082(bucket_sizes_332_fu_128),
    .bucket_sizes_1081(bucket_sizes_331_fu_124),
    .bucket_sizes_1080(bucket_sizes_fu_120),
    .bucket_pointer_470(bucket_pointer_272_fu_116),
    .bucket_pointer_469(bucket_pointer_271_fu_112),
    .bucket_pointer_468(bucket_pointer_270_fu_108),
    .bucket_pointer_467(bucket_pointer_269_fu_104),
    .bucket_pointer_466(bucket_pointer_268_fu_100),
    .bucket_pointer_465(bucket_pointer_267_fu_96),
    .bucket_pointer_464(bucket_pointer_266_fu_92),
    .bucket_pointer_463(bucket_pointer_265_fu_88),
    .bucket_pointer_462(bucket_pointer_264_fu_84),
    .bucket_pointer_461(bucket_pointer_263_fu_80),
    .bucket_pointer_460(bucket_pointer_262_fu_76),
    .bucket_pointer_459(bucket_pointer_261_fu_72),
    .bucket_pointer_458(bucket_pointer_260_fu_68),
    .bucket_pointer_457(bucket_pointer_259_fu_64),
    .bucket_pointer_456(bucket_pointer_258_fu_60),
    .bucket_pointer(bucket_pointer_fu_56),
    .bucket_sizes_1111_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1111_out),
    .bucket_sizes_1111_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1111_out_ap_vld),
    .bucket_sizes_1110_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1110_out),
    .bucket_sizes_1110_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1110_out_ap_vld),
    .bucket_sizes_1109_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1109_out),
    .bucket_sizes_1109_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1109_out_ap_vld),
    .bucket_sizes_1108_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1108_out),
    .bucket_sizes_1108_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1108_out_ap_vld),
    .bucket_sizes_1107_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1107_out),
    .bucket_sizes_1107_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1107_out_ap_vld),
    .bucket_sizes_1106_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1106_out),
    .bucket_sizes_1106_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1106_out_ap_vld),
    .bucket_sizes_1105_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1105_out),
    .bucket_sizes_1105_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1105_out_ap_vld),
    .bucket_sizes_1104_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1104_out),
    .bucket_sizes_1104_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1104_out_ap_vld),
    .bucket_sizes_1103_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1103_out),
    .bucket_sizes_1103_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1103_out_ap_vld),
    .bucket_sizes_1102_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1102_out),
    .bucket_sizes_1102_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1102_out_ap_vld),
    .bucket_sizes_1101_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1101_out),
    .bucket_sizes_1101_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1101_out_ap_vld),
    .bucket_sizes_1100_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1100_out),
    .bucket_sizes_1100_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1100_out_ap_vld),
    .bucket_sizes_1099_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1099_out),
    .bucket_sizes_1099_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1099_out_ap_vld),
    .bucket_sizes_1098_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1098_out),
    .bucket_sizes_1098_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1098_out_ap_vld),
    .bucket_sizes_1097_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1097_out),
    .bucket_sizes_1097_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1097_out_ap_vld),
    .bucket_sizes_1096_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1096_out),
    .bucket_sizes_1096_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1096_out_ap_vld),
    .bucket_pointer_486_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_486_out),
    .bucket_pointer_486_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_486_out_ap_vld),
    .bucket_pointer_485_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_485_out),
    .bucket_pointer_485_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_485_out_ap_vld),
    .bucket_pointer_484_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_484_out),
    .bucket_pointer_484_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_484_out_ap_vld),
    .bucket_pointer_483_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_483_out),
    .bucket_pointer_483_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_483_out_ap_vld),
    .bucket_pointer_482_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_482_out),
    .bucket_pointer_482_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_482_out_ap_vld),
    .bucket_pointer_481_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_481_out),
    .bucket_pointer_481_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_481_out_ap_vld),
    .bucket_pointer_480_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_480_out),
    .bucket_pointer_480_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_480_out_ap_vld),
    .bucket_pointer_479_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_479_out),
    .bucket_pointer_479_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_479_out_ap_vld),
    .bucket_pointer_478_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_478_out),
    .bucket_pointer_478_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_478_out_ap_vld),
    .bucket_pointer_477_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_477_out),
    .bucket_pointer_477_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_477_out_ap_vld),
    .bucket_pointer_476_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_476_out),
    .bucket_pointer_476_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_476_out_ap_vld),
    .bucket_pointer_475_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_475_out),
    .bucket_pointer_475_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_475_out_ap_vld),
    .bucket_pointer_474_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_474_out),
    .bucket_pointer_474_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_474_out_ap_vld),
    .bucket_pointer_473_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_473_out),
    .bucket_pointer_473_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_473_out_ap_vld),
    .bucket_pointer_472_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_472_out),
    .bucket_pointer_472_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_472_out_ap_vld),
    .bucket_pointer_471_out(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_471_out),
    .bucket_pointer_471_out_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_471_out_ap_vld)
);

multi_radix_hex_loser_radix_sort_hex_batch_6_1_Pipeline_output_bucket grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start),
    .ap_done(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_done),
    .ap_idle(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_idle),
    .ap_ready(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_ready),
    .bucket_address0(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_bucket_address0),
    .bucket_ce0(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_bucket_ce0),
    .bucket_q0(bucket_q0),
    .multi_radix_hex_loser_temp0_5_address0(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_address0),
    .multi_radix_hex_loser_temp0_5_ce0(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_ce0),
    .multi_radix_hex_loser_temp0_5_we0(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_we0),
    .multi_radix_hex_loser_temp0_5_d0(grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_d0)
);

multi_radix_hex_loser_radix_sort_hex_batch_6_1_Pipeline_input_bucket grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start),
    .ap_done(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_done),
    .ap_idle(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_idle),
    .ap_ready(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_ready),
    .bucket_sizes_1111_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1111_out),
    .bucket_sizes_1110_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1110_out),
    .bucket_sizes_1109_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1109_out),
    .bucket_sizes_1108_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1108_out),
    .bucket_sizes_1107_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1107_out),
    .bucket_sizes_1106_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1106_out),
    .bucket_sizes_1105_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1105_out),
    .bucket_sizes_1104_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1104_out),
    .bucket_sizes_1103_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1103_out),
    .bucket_sizes_1102_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1102_out),
    .bucket_sizes_1101_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1101_out),
    .bucket_sizes_1100_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1100_out),
    .bucket_sizes_1099_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1099_out),
    .bucket_sizes_1098_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1098_out),
    .bucket_sizes_1097_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1097_out),
    .bucket_sizes_1096_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_sizes_1096_out),
    .bucket_pointer_486_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_486_out),
    .bucket_pointer_485_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_485_out),
    .bucket_pointer_484_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_484_out),
    .bucket_pointer_483_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_483_out),
    .bucket_pointer_482_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_482_out),
    .bucket_pointer_481_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_481_out),
    .bucket_pointer_480_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_480_out),
    .bucket_pointer_479_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_479_out),
    .bucket_pointer_478_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_478_out),
    .bucket_pointer_477_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_477_out),
    .bucket_pointer_476_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_476_out),
    .bucket_pointer_475_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_475_out),
    .bucket_pointer_474_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_474_out),
    .bucket_pointer_473_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_473_out),
    .bucket_pointer_472_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_472_out),
    .bucket_pointer_471_reload(grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_bucket_pointer_471_out),
    .mul_ln41(mul_ln41_reg_1752),
    .bucket_address0(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_address0),
    .bucket_ce0(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_ce0),
    .bucket_we0(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_we0),
    .bucket_d0(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_d0),
    .bucket_address1(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_address1),
    .bucket_ce1(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_ce1),
    .bucket_q1(bucket_q1),
    .mul_cast_i(mul_i_reg_1757),
    .mul_ln43(mul_ln43_reg_1762),
    .bucket_sizes_1143_out_i(bucket_sizes_345_fu_180),
    .bucket_sizes_1143_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1143_out_o),
    .bucket_sizes_1143_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1143_out_o_ap_vld),
    .bucket_sizes_1142_out_i(bucket_sizes_344_fu_176),
    .bucket_sizes_1142_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1142_out_o),
    .bucket_sizes_1142_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1142_out_o_ap_vld),
    .bucket_sizes_1141_out_i(bucket_sizes_343_fu_172),
    .bucket_sizes_1141_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1141_out_o),
    .bucket_sizes_1141_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1141_out_o_ap_vld),
    .bucket_sizes_1140_out_i(bucket_sizes_342_fu_168),
    .bucket_sizes_1140_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1140_out_o),
    .bucket_sizes_1140_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1140_out_o_ap_vld),
    .bucket_sizes_1139_out_i(bucket_sizes_341_fu_164),
    .bucket_sizes_1139_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1139_out_o),
    .bucket_sizes_1139_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1139_out_o_ap_vld),
    .bucket_sizes_1138_out_i(bucket_sizes_340_fu_160),
    .bucket_sizes_1138_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1138_out_o),
    .bucket_sizes_1138_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1138_out_o_ap_vld),
    .bucket_sizes_1137_out_i(bucket_sizes_339_fu_156),
    .bucket_sizes_1137_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1137_out_o),
    .bucket_sizes_1137_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1137_out_o_ap_vld),
    .bucket_sizes_1136_out_i(bucket_sizes_338_fu_152),
    .bucket_sizes_1136_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1136_out_o),
    .bucket_sizes_1136_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1136_out_o_ap_vld),
    .bucket_sizes_1135_out_i(bucket_sizes_337_fu_148),
    .bucket_sizes_1135_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1135_out_o),
    .bucket_sizes_1135_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1135_out_o_ap_vld),
    .bucket_sizes_1134_out_i(bucket_sizes_336_fu_144),
    .bucket_sizes_1134_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1134_out_o),
    .bucket_sizes_1134_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1134_out_o_ap_vld),
    .bucket_sizes_1133_out_i(bucket_sizes_335_fu_140),
    .bucket_sizes_1133_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1133_out_o),
    .bucket_sizes_1133_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1133_out_o_ap_vld),
    .bucket_sizes_1132_out_i(bucket_sizes_334_fu_136),
    .bucket_sizes_1132_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1132_out_o),
    .bucket_sizes_1132_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1132_out_o_ap_vld),
    .bucket_sizes_1131_out_i(bucket_sizes_333_fu_132),
    .bucket_sizes_1131_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1131_out_o),
    .bucket_sizes_1131_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1131_out_o_ap_vld),
    .bucket_sizes_1130_out_i(bucket_sizes_332_fu_128),
    .bucket_sizes_1130_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1130_out_o),
    .bucket_sizes_1130_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1130_out_o_ap_vld),
    .bucket_sizes_1129_out_i(bucket_sizes_331_fu_124),
    .bucket_sizes_1129_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1129_out_o),
    .bucket_sizes_1129_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1129_out_o_ap_vld),
    .bucket_sizes_1128_out_i(bucket_sizes_fu_120),
    .bucket_sizes_1128_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1128_out_o),
    .bucket_sizes_1128_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1128_out_o_ap_vld),
    .bucket_pointer_503_out_i(bucket_pointer_272_fu_116),
    .bucket_pointer_503_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_503_out_o),
    .bucket_pointer_503_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_503_out_o_ap_vld),
    .bucket_pointer_502_out_i(bucket_pointer_271_fu_112),
    .bucket_pointer_502_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_502_out_o),
    .bucket_pointer_502_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_502_out_o_ap_vld),
    .bucket_pointer_501_out_i(bucket_pointer_270_fu_108),
    .bucket_pointer_501_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_501_out_o),
    .bucket_pointer_501_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_501_out_o_ap_vld),
    .bucket_pointer_500_out_i(bucket_pointer_269_fu_104),
    .bucket_pointer_500_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_500_out_o),
    .bucket_pointer_500_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_500_out_o_ap_vld),
    .bucket_pointer_499_out_i(bucket_pointer_268_fu_100),
    .bucket_pointer_499_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_499_out_o),
    .bucket_pointer_499_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_499_out_o_ap_vld),
    .bucket_pointer_498_out_i(bucket_pointer_267_fu_96),
    .bucket_pointer_498_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_498_out_o),
    .bucket_pointer_498_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_498_out_o_ap_vld),
    .bucket_pointer_497_out_i(bucket_pointer_266_fu_92),
    .bucket_pointer_497_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_497_out_o),
    .bucket_pointer_497_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_497_out_o_ap_vld),
    .bucket_pointer_496_out_i(bucket_pointer_265_fu_88),
    .bucket_pointer_496_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_496_out_o),
    .bucket_pointer_496_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_496_out_o_ap_vld),
    .bucket_pointer_495_out_i(bucket_pointer_264_fu_84),
    .bucket_pointer_495_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_495_out_o),
    .bucket_pointer_495_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_495_out_o_ap_vld),
    .bucket_pointer_494_out_i(bucket_pointer_263_fu_80),
    .bucket_pointer_494_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_494_out_o),
    .bucket_pointer_494_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_494_out_o_ap_vld),
    .bucket_pointer_493_out_i(bucket_pointer_262_fu_76),
    .bucket_pointer_493_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_493_out_o),
    .bucket_pointer_493_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_493_out_o_ap_vld),
    .bucket_pointer_492_out_i(bucket_pointer_261_fu_72),
    .bucket_pointer_492_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_492_out_o),
    .bucket_pointer_492_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_492_out_o_ap_vld),
    .bucket_pointer_491_out_i(bucket_pointer_260_fu_68),
    .bucket_pointer_491_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_491_out_o),
    .bucket_pointer_491_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_491_out_o_ap_vld),
    .bucket_pointer_490_out_i(bucket_pointer_259_fu_64),
    .bucket_pointer_490_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_490_out_o),
    .bucket_pointer_490_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_490_out_o_ap_vld),
    .bucket_pointer_489_out_i(bucket_pointer_258_fu_60),
    .bucket_pointer_489_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_489_out_o),
    .bucket_pointer_489_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_489_out_o_ap_vld),
    .bucket_pointer_488_out_i(bucket_pointer_fu_56),
    .bucket_pointer_488_out_o(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_488_out_o),
    .bucket_pointer_488_out_o_ap_vld(grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_488_out_o_ap_vld)
);

multi_radix_hex_loser_mul_mul_15s_14ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 15 ))
mul_mul_15s_14ns_15_4_1_U1156(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_970_p0),
    .din1(grp_fu_970_p1),
    .ce(grp_fu_970_ce),
    .dout(grp_fu_970_p2)
);

multi_radix_hex_loser_mul_mul_15s_14ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 15 ))
mul_mul_15s_14ns_15_4_1_U1157(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_977_p0),
    .din1(grp_fu_977_p1),
    .ce(grp_fu_977_ce),
    .dout(grp_fu_977_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_ready == 1'b1)) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln27_fu_663_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_ready == 1'b1)) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_ready == 1'b1)) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_ready == 1'b1)) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln27_fu_663_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_ready == 1'b1)) begin
            grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_num_fu_52 <= 32'd0;
    end else if (((icmp_ln27_fu_663_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        bucket_num_fu_52 <= bucket_num_8_fu_806_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1129_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_331_fu_124 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1129_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1048_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_331_fu_124 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1048_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1130_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_332_fu_128 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1130_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1049_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_332_fu_128 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1049_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1131_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_333_fu_132 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1131_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1050_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_333_fu_132 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1050_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1132_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_334_fu_136 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1132_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1051_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_334_fu_136 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1051_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1133_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_335_fu_140 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1133_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1052_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_335_fu_140 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1052_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1134_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_336_fu_144 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1134_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1053_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_336_fu_144 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1053_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1135_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_337_fu_148 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1135_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1054_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_337_fu_148 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1054_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1136_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_338_fu_152 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1136_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1055_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_338_fu_152 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1055_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1137_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_339_fu_156 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1137_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1056_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_339_fu_156 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1056_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1138_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_340_fu_160 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1138_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1057_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_340_fu_160 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1057_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1139_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_341_fu_164 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1139_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1058_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_341_fu_164 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1058_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1140_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_342_fu_168 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1140_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1059_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_342_fu_168 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1059_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1141_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_343_fu_172 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1141_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1060_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_343_fu_172 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1060_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1142_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_344_fu_176 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1142_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1061_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_344_fu_176 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1061_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1143_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_345_fu_180 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1143_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1062_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_345_fu_180 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1062_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1128_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_fu_120 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_sizes_1128_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1047_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_fu_120 <= grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_sizes_1047_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_48 <= 4'd0;
    end else if (((icmp_ln27_fu_663_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        i_fu_48 <= i_16_fu_669_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_489_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_258_fu_60 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_489_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_490_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_259_fu_64 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_490_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_491_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_260_fu_68 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_491_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_492_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_261_fu_72 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_492_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_493_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_262_fu_76 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_493_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_494_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_263_fu_80 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_494_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_495_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_264_fu_84 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_495_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_496_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_265_fu_88 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_496_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_497_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_266_fu_92 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_497_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_498_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_267_fu_96 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_498_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_499_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_268_fu_100 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_499_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_500_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_269_fu_104 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_500_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_501_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_270_fu_108 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_501_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_502_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_271_fu_112 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_502_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_503_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_272_fu_116 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_503_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_488_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_fu_56 <= grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_pointer_488_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_663_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_108_reg_1646 <= empty_108_fu_816_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul_i_reg_1757[4 : 2] <= mul_i_fu_962_p3[4 : 2];
        mul_ln41_reg_1752 <= grp_fu_970_p2;
        mul_ln43_reg_1762 <= grp_fu_977_p2;
    end
end

always @ (*) begin
    if ((grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_address0 = grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        bucket_address0 = grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_bucket_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_address0 = grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_address0;
    end else begin
        bucket_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_ce0 = grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        bucket_ce0 = grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_bucket_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_ce0 = grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_ce0;
    end else begin
        bucket_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_ce1 = grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_ce1;
    end else begin
        bucket_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_d0 = grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_d0 = grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_d0;
    end else begin
        bucket_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_we0 = grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_bucket_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_we0 = grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_bucket_we0;
    end else begin
        bucket_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | ((grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_fu_970_ce = 1'b1;
    end else begin
        grp_fu_970_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | ((grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_fu_977_ce = 1'b1;
    end else begin
        grp_fu_977_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln27_fu_663_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call84 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bucket_num_8_fu_806_p2 = (32'd1 - bucket_num_fu_52);

assign empty_108_fu_816_p1 = i_fu_48[2:0];

assign grp_fu_970_p0 = bucket_num_8_fu_806_p2[14:0];

assign grp_fu_970_p1 = 15'd15625;

assign grp_fu_977_p0 = bucket_num_fu_52[14:0];

assign grp_fu_977_p1 = 15'd15625;

assign grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start = grp_radix_sort_hex_batch_6_1_Pipeline_1_fu_380_ap_start_reg;

assign grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start = grp_radix_sort_hex_batch_6_1_Pipeline_bucket_pointer_initialization_fu_439_ap_start_reg;

assign grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start = grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_ap_start_reg;

assign grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start = grp_radix_sort_hex_batch_6_1_Pipeline_input_bucket_fu_514_ap_start_reg;

assign grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start = grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_ap_start_reg;

assign i_16_fu_669_p2 = (i_fu_48 + 4'd1);

assign icmp_ln27_fu_663_p2 = ((i_fu_48 == 4'd8) ? 1'b1 : 1'b0);

assign input_5_address0 = grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_input_5_address0;

assign input_5_ce0 = grp_radix_sort_hex_batch_6_1_Pipeline_initialization_fu_400_input_5_ce0;

assign mul_i_fu_962_p3 = {{empty_108_reg_1646}, {2'd0}};

assign multi_radix_hex_loser_temp0_5_address0 = grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_address0;

assign multi_radix_hex_loser_temp0_5_ce0 = grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_ce0;

assign multi_radix_hex_loser_temp0_5_d0 = grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_d0;

assign multi_radix_hex_loser_temp0_5_we0 = grp_radix_sort_hex_batch_6_1_Pipeline_output_bucket_fu_507_multi_radix_hex_loser_temp0_5_we0;

always @ (posedge ap_clk) begin
    mul_i_reg_1757[1:0] <= 2'b00;
end

endmodule //multi_radix_hex_loser_radix_sort_hex_batch_6_1
