// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module multi_radix_oct_loser_64_radix_sort_oct_batch_53_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_52_address0,
        input_52_ce0,
        input_52_q0,
        multi_radix_oct_loser_64_temp0_52_address0,
        multi_radix_oct_loser_64_temp0_52_ce0,
        multi_radix_oct_loser_64_temp0_52_we0,
        multi_radix_oct_loser_64_temp0_52_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [17:0] input_52_address0;
output   input_52_ce0;
input  [31:0] input_52_q0;
output  [17:0] multi_radix_oct_loser_64_temp0_52_address0;
output   multi_radix_oct_loser_64_temp0_52_ce0;
output   multi_radix_oct_loser_64_temp0_52_we0;
output  [31:0] multi_radix_oct_loser_64_temp0_52_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] i_29_reg_871;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln27_fu_383_p2;
wire  signed [18:0] grp_fu_571_p2;
reg   [18:0] mul_ln41_reg_986;
wire    ap_CS_fsm_state8;
wire   [6:0] mul_i_fu_564_p2;
reg   [6:0] mul_i_reg_991;
wire  signed [18:0] grp_fu_578_p2;
reg   [18:0] mul_ln43_reg_996;
reg   [18:0] bucket_address0;
reg    bucket_ce0;
reg    bucket_we0;
reg   [31:0] bucket_d0;
wire   [31:0] bucket_q0;
reg    bucket_ce1;
wire   [31:0] bucket_q1;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_done;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_idle;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_ready;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1029_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1029_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1028_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1028_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1027_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1027_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1026_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1026_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1025_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1025_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1024_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1024_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1023_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1023_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_out_ap_vld;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_done;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_idle;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_ready;
wire   [18:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_address0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_ce0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_we0;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_d0;
wire   [17:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_input_52_address0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_input_52_ce0;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1045_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1045_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1044_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1044_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1043_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1043_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1042_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1042_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1041_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1041_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1040_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1040_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1039_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1039_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1038_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1038_out_o_ap_vld;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_idle;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_ready;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1070_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1070_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1069_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1069_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1068_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1068_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1067_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1067_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1066_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1066_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1065_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1065_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1064_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1064_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1063_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1063_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_477_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_477_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_476_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_476_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_475_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_475_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_474_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_474_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_473_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_473_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_472_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_472_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_471_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_471_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_470_out;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_470_out_ap_vld;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_done;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_idle;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_ready;
wire   [18:0] grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_bucket_address0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_bucket_ce0;
wire   [17:0] grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_address0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_ce0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_we0;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_d0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_done;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_idle;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_ready;
wire   [18:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_address0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_ce0;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_we0;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_d0;
wire   [18:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_address1;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_ce1;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1086_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1086_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1085_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1085_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1084_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1084_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1083_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1083_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1082_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1082_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1081_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1081_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1080_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1080_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1079_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1079_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_486_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_486_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_485_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_485_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_484_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_484_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_483_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_483_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_482_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_482_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_481_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_481_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_480_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_480_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_479_out_o;
wire    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_479_out_o_ap_vld;
reg    grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start_reg;
reg    ap_block_state1_ignore_call44;
wire    ap_CS_fsm_state2;
reg    grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] bucket_sizes_308_fu_116;
reg   [31:0] bucket_sizes_307_fu_112;
reg   [31:0] bucket_sizes_306_fu_108;
reg   [31:0] bucket_sizes_305_fu_104;
reg   [31:0] bucket_sizes_304_fu_100;
reg   [31:0] bucket_sizes_303_fu_96;
reg   [31:0] bucket_sizes_302_fu_92;
reg   [31:0] bucket_sizes_fu_88;
reg    grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [31:0] bucket_pointer_270_fu_84;
reg   [31:0] bucket_pointer_269_fu_80;
reg   [31:0] bucket_pointer_268_fu_76;
reg   [31:0] bucket_pointer_267_fu_72;
reg   [31:0] bucket_pointer_266_fu_68;
reg   [31:0] bucket_pointer_265_fu_64;
reg   [31:0] bucket_pointer_264_fu_60;
reg   [31:0] bucket_pointer_fu_56;
reg   [3:0] i_fu_48;
wire   [3:0] i_30_fu_389_p2;
reg    ap_block_state1;
reg   [31:0] bucket_num_fu_52;
wire   [31:0] bucket_num_15_fu_462_p2;
wire   [5:0] p_shl_i_fu_553_p3;
wire   [6:0] p_shl_cast_i_fu_560_p1;
wire   [6:0] zext_ln27_fu_486_p1;
wire  signed [18:0] grp_fu_571_p0;
wire   [17:0] grp_fu_571_p1;
wire  signed [18:0] grp_fu_578_p0;
wire   [17:0] grp_fu_578_p1;
reg    grp_fu_571_ce;
wire    ap_CS_fsm_state7;
reg    grp_fu_578_ce;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start_reg = 1'b0;
end

multi_radix_oct_loser_64_radix_sort_oct_batch_53_1_bucket_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 312500 ),
    .AddressWidth( 19 ))
bucket_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bucket_address0),
    .ce0(bucket_ce0),
    .we0(bucket_we0),
    .d0(bucket_d0),
    .q0(bucket_q0),
    .address1(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_address1),
    .ce1(bucket_ce1),
    .q1(bucket_q1)
);

multi_radix_oct_loser_64_radix_sort_oct_batch_53_1_Pipeline_1 grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start),
    .ap_done(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_ready),
    .bucket_sizes_1029_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1029_out),
    .bucket_sizes_1029_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1029_out_ap_vld),
    .bucket_sizes_1028_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1028_out),
    .bucket_sizes_1028_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1028_out_ap_vld),
    .bucket_sizes_1027_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1027_out),
    .bucket_sizes_1027_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1027_out_ap_vld),
    .bucket_sizes_1026_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1026_out),
    .bucket_sizes_1026_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1026_out_ap_vld),
    .bucket_sizes_1025_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1025_out),
    .bucket_sizes_1025_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1025_out_ap_vld),
    .bucket_sizes_1024_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1024_out),
    .bucket_sizes_1024_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1024_out_ap_vld),
    .bucket_sizes_1023_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1023_out),
    .bucket_sizes_1023_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1023_out_ap_vld),
    .bucket_sizes_out(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_out),
    .bucket_sizes_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_out_ap_vld)
);

multi_radix_oct_loser_64_radix_sort_oct_batch_53_1_Pipeline_initialization grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start),
    .ap_done(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_ready),
    .bucket_sizes_1029_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1029_out),
    .bucket_sizes_1028_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1028_out),
    .bucket_sizes_1027_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1027_out),
    .bucket_sizes_1026_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1026_out),
    .bucket_sizes_1025_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1025_out),
    .bucket_sizes_1024_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1024_out),
    .bucket_sizes_1023_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_1023_out),
    .bucket_sizes_reload(grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_bucket_sizes_out),
    .bucket_address0(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_address0),
    .bucket_ce0(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_ce0),
    .bucket_we0(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_we0),
    .bucket_d0(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_d0),
    .input_52_address0(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_input_52_address0),
    .input_52_ce0(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_input_52_ce0),
    .input_52_q0(input_52_q0),
    .bucket_sizes_1045_out_i(bucket_sizes_308_fu_116),
    .bucket_sizes_1045_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1045_out_o),
    .bucket_sizes_1045_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1045_out_o_ap_vld),
    .bucket_sizes_1044_out_i(bucket_sizes_307_fu_112),
    .bucket_sizes_1044_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1044_out_o),
    .bucket_sizes_1044_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1044_out_o_ap_vld),
    .bucket_sizes_1043_out_i(bucket_sizes_306_fu_108),
    .bucket_sizes_1043_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1043_out_o),
    .bucket_sizes_1043_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1043_out_o_ap_vld),
    .bucket_sizes_1042_out_i(bucket_sizes_305_fu_104),
    .bucket_sizes_1042_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1042_out_o),
    .bucket_sizes_1042_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1042_out_o_ap_vld),
    .bucket_sizes_1041_out_i(bucket_sizes_304_fu_100),
    .bucket_sizes_1041_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1041_out_o),
    .bucket_sizes_1041_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1041_out_o_ap_vld),
    .bucket_sizes_1040_out_i(bucket_sizes_303_fu_96),
    .bucket_sizes_1040_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1040_out_o),
    .bucket_sizes_1040_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1040_out_o_ap_vld),
    .bucket_sizes_1039_out_i(bucket_sizes_302_fu_92),
    .bucket_sizes_1039_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1039_out_o),
    .bucket_sizes_1039_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1039_out_o_ap_vld),
    .bucket_sizes_1038_out_i(bucket_sizes_fu_88),
    .bucket_sizes_1038_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1038_out_o),
    .bucket_sizes_1038_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1038_out_o_ap_vld)
);

multi_radix_oct_loser_64_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start),
    .ap_done(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_ready),
    .bucket_sizes_1062(bucket_sizes_308_fu_116),
    .bucket_sizes_1061(bucket_sizes_307_fu_112),
    .bucket_sizes_1060(bucket_sizes_306_fu_108),
    .bucket_sizes_1059(bucket_sizes_305_fu_104),
    .bucket_sizes_1058(bucket_sizes_304_fu_100),
    .bucket_sizes_1057(bucket_sizes_303_fu_96),
    .bucket_sizes_1056(bucket_sizes_302_fu_92),
    .bucket_sizes_1055(bucket_sizes_fu_88),
    .bucket_pointer_469(bucket_pointer_270_fu_84),
    .bucket_pointer_468(bucket_pointer_269_fu_80),
    .bucket_pointer_467(bucket_pointer_268_fu_76),
    .bucket_pointer_466(bucket_pointer_267_fu_72),
    .bucket_pointer_465(bucket_pointer_266_fu_68),
    .bucket_pointer_464(bucket_pointer_265_fu_64),
    .bucket_pointer_463(bucket_pointer_264_fu_60),
    .bucket_pointer(bucket_pointer_fu_56),
    .bucket_sizes_1070_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1070_out),
    .bucket_sizes_1070_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1070_out_ap_vld),
    .bucket_sizes_1069_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1069_out),
    .bucket_sizes_1069_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1069_out_ap_vld),
    .bucket_sizes_1068_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1068_out),
    .bucket_sizes_1068_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1068_out_ap_vld),
    .bucket_sizes_1067_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1067_out),
    .bucket_sizes_1067_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1067_out_ap_vld),
    .bucket_sizes_1066_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1066_out),
    .bucket_sizes_1066_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1066_out_ap_vld),
    .bucket_sizes_1065_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1065_out),
    .bucket_sizes_1065_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1065_out_ap_vld),
    .bucket_sizes_1064_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1064_out),
    .bucket_sizes_1064_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1064_out_ap_vld),
    .bucket_sizes_1063_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1063_out),
    .bucket_sizes_1063_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1063_out_ap_vld),
    .bucket_pointer_477_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_477_out),
    .bucket_pointer_477_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_477_out_ap_vld),
    .bucket_pointer_476_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_476_out),
    .bucket_pointer_476_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_476_out_ap_vld),
    .bucket_pointer_475_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_475_out),
    .bucket_pointer_475_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_475_out_ap_vld),
    .bucket_pointer_474_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_474_out),
    .bucket_pointer_474_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_474_out_ap_vld),
    .bucket_pointer_473_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_473_out),
    .bucket_pointer_473_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_473_out_ap_vld),
    .bucket_pointer_472_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_472_out),
    .bucket_pointer_472_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_472_out_ap_vld),
    .bucket_pointer_471_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_471_out),
    .bucket_pointer_471_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_471_out_ap_vld),
    .bucket_pointer_470_out(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_470_out),
    .bucket_pointer_470_out_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_470_out_ap_vld)
);

multi_radix_oct_loser_64_radix_sort_oct_batch_53_1_Pipeline_output_bucket grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start),
    .ap_done(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_ready),
    .bucket_address0(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_bucket_address0),
    .bucket_ce0(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_bucket_ce0),
    .bucket_q0(bucket_q0),
    .multi_radix_oct_loser_64_temp0_52_address0(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_address0),
    .multi_radix_oct_loser_64_temp0_52_ce0(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_ce0),
    .multi_radix_oct_loser_64_temp0_52_we0(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_we0),
    .multi_radix_oct_loser_64_temp0_52_d0(grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_d0)
);

multi_radix_oct_loser_64_radix_sort_oct_batch_53_1_Pipeline_input_bucket grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start),
    .ap_done(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_ready),
    .bucket_sizes_1070_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1070_out),
    .bucket_sizes_1069_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1069_out),
    .bucket_sizes_1068_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1068_out),
    .bucket_sizes_1067_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1067_out),
    .bucket_sizes_1066_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1066_out),
    .bucket_sizes_1065_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1065_out),
    .bucket_sizes_1064_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1064_out),
    .bucket_sizes_1063_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_1063_out),
    .bucket_pointer_477_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_477_out),
    .bucket_pointer_476_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_476_out),
    .bucket_pointer_475_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_475_out),
    .bucket_pointer_474_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_474_out),
    .bucket_pointer_473_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_473_out),
    .bucket_pointer_472_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_472_out),
    .bucket_pointer_471_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_471_out),
    .bucket_pointer_470_reload(grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_470_out),
    .mul_ln41(mul_ln41_reg_986),
    .bucket_address0(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_address0),
    .bucket_ce0(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_ce0),
    .bucket_we0(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_we0),
    .bucket_d0(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_d0),
    .bucket_address1(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_address1),
    .bucket_ce1(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_ce1),
    .bucket_q1(bucket_q1),
    .mul_cast_i(mul_i_reg_991),
    .mul_ln43(mul_ln43_reg_996),
    .bucket_sizes_1086_out_i(bucket_sizes_308_fu_116),
    .bucket_sizes_1086_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1086_out_o),
    .bucket_sizes_1086_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1086_out_o_ap_vld),
    .bucket_sizes_1085_out_i(bucket_sizes_307_fu_112),
    .bucket_sizes_1085_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1085_out_o),
    .bucket_sizes_1085_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1085_out_o_ap_vld),
    .bucket_sizes_1084_out_i(bucket_sizes_306_fu_108),
    .bucket_sizes_1084_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1084_out_o),
    .bucket_sizes_1084_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1084_out_o_ap_vld),
    .bucket_sizes_1083_out_i(bucket_sizes_305_fu_104),
    .bucket_sizes_1083_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1083_out_o),
    .bucket_sizes_1083_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1083_out_o_ap_vld),
    .bucket_sizes_1082_out_i(bucket_sizes_304_fu_100),
    .bucket_sizes_1082_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1082_out_o),
    .bucket_sizes_1082_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1082_out_o_ap_vld),
    .bucket_sizes_1081_out_i(bucket_sizes_303_fu_96),
    .bucket_sizes_1081_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1081_out_o),
    .bucket_sizes_1081_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1081_out_o_ap_vld),
    .bucket_sizes_1080_out_i(bucket_sizes_302_fu_92),
    .bucket_sizes_1080_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1080_out_o),
    .bucket_sizes_1080_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1080_out_o_ap_vld),
    .bucket_sizes_1079_out_i(bucket_sizes_fu_88),
    .bucket_sizes_1079_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1079_out_o),
    .bucket_sizes_1079_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1079_out_o_ap_vld),
    .bucket_pointer_486_out_i(bucket_pointer_270_fu_84),
    .bucket_pointer_486_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_486_out_o),
    .bucket_pointer_486_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_486_out_o_ap_vld),
    .bucket_pointer_485_out_i(bucket_pointer_269_fu_80),
    .bucket_pointer_485_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_485_out_o),
    .bucket_pointer_485_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_485_out_o_ap_vld),
    .bucket_pointer_484_out_i(bucket_pointer_268_fu_76),
    .bucket_pointer_484_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_484_out_o),
    .bucket_pointer_484_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_484_out_o_ap_vld),
    .bucket_pointer_483_out_i(bucket_pointer_267_fu_72),
    .bucket_pointer_483_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_483_out_o),
    .bucket_pointer_483_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_483_out_o_ap_vld),
    .bucket_pointer_482_out_i(bucket_pointer_266_fu_68),
    .bucket_pointer_482_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_482_out_o),
    .bucket_pointer_482_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_482_out_o_ap_vld),
    .bucket_pointer_481_out_i(bucket_pointer_265_fu_64),
    .bucket_pointer_481_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_481_out_o),
    .bucket_pointer_481_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_481_out_o_ap_vld),
    .bucket_pointer_480_out_i(bucket_pointer_264_fu_60),
    .bucket_pointer_480_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_480_out_o),
    .bucket_pointer_480_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_480_out_o_ap_vld),
    .bucket_pointer_479_out_i(bucket_pointer_fu_56),
    .bucket_pointer_479_out_o(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_479_out_o),
    .bucket_pointer_479_out_o_ap_vld(grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_479_out_o_ap_vld)
);

multi_radix_oct_loser_64_mul_mul_19s_18ns_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mul_mul_19s_18ns_19_4_1_U5563(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_571_p0),
    .din1(grp_fu_571_p1),
    .ce(grp_fu_571_ce),
    .dout(grp_fu_571_p2)
);

multi_radix_oct_loser_64_mul_mul_19s_18ns_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mul_mul_19s_18ns_19_4_1_U5564(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_578_p0),
    .din1(grp_fu_578_p1),
    .ce(grp_fu_578_ce),
    .dout(grp_fu_578_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln27_fu_383_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln27_fu_383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_num_fu_52 <= 32'd0;
    end else if (((icmp_ln27_fu_383_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        bucket_num_fu_52 <= bucket_num_15_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1080_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_302_fu_92 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1080_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1039_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_302_fu_92 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1039_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1081_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_303_fu_96 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1081_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1040_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_303_fu_96 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1040_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1082_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_304_fu_100 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1082_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1041_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_304_fu_100 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1041_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1083_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_305_fu_104 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1083_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1042_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_305_fu_104 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1042_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1084_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_306_fu_108 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1084_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1043_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_306_fu_108 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1043_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1085_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_307_fu_112 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1085_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1044_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_307_fu_112 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1044_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1086_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_308_fu_116 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1086_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1045_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_308_fu_116 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1045_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1079_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_fu_88 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_sizes_1079_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1038_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_fu_88 <= grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_sizes_1038_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_48 <= 4'd0;
    end else if (((icmp_ln27_fu_383_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        i_fu_48 <= i_30_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_480_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_264_fu_60 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_480_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_481_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_265_fu_64 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_481_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_482_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_266_fu_68 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_482_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_483_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_267_fu_72 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_483_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_484_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_268_fu_76 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_484_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_485_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_269_fu_80 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_485_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_486_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_270_fu_84 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_486_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_479_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_fu_56 <= grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_pointer_479_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_29_reg_871 <= i_fu_48;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul_i_reg_991 <= mul_i_fu_564_p2;
        mul_ln41_reg_986 <= grp_fu_571_p2;
        mul_ln43_reg_996 <= grp_fu_578_p2;
    end
end

always @ (*) begin
    if ((grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_address0 = grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        bucket_address0 = grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_bucket_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_address0 = grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_address0;
    end else begin
        bucket_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_ce0 = grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        bucket_ce0 = grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_bucket_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_ce0 = grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_ce0;
    end else begin
        bucket_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_ce1 = grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_ce1;
    end else begin
        bucket_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_d0 = grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_d0 = grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_d0;
    end else begin
        bucket_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_we0 = grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_bucket_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_we0 = grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_bucket_we0;
    end else begin
        bucket_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b1)))) begin
        grp_fu_571_ce = 1'b1;
    end else begin
        grp_fu_571_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b1)))) begin
        grp_fu_578_ce = 1'b1;
    end else begin
        grp_fu_578_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln27_fu_383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call44 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bucket_num_15_fu_462_p2 = (32'd1 - bucket_num_fu_52);

assign grp_fu_571_p0 = bucket_num_15_fu_462_p2[18:0];

assign grp_fu_571_p1 = 19'd156250;

assign grp_fu_578_p0 = bucket_num_fu_52[18:0];

assign grp_fu_578_p1 = 19'd156250;

assign grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start = grp_radix_sort_oct_batch_53_1_Pipeline_1_fu_220_ap_start_reg;

assign grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start = grp_radix_sort_oct_batch_53_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg;

assign grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start = grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_ap_start_reg;

assign grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start = grp_radix_sort_oct_batch_53_1_Pipeline_input_bucket_fu_298_ap_start_reg;

assign grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start = grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_ap_start_reg;

assign i_30_fu_389_p2 = (i_fu_48 + 4'd1);

assign icmp_ln27_fu_383_p2 = ((i_fu_48 == 4'd11) ? 1'b1 : 1'b0);

assign input_52_address0 = grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_input_52_address0;

assign input_52_ce0 = grp_radix_sort_oct_batch_53_1_Pipeline_initialization_fu_232_input_52_ce0;

assign mul_i_fu_564_p2 = (p_shl_cast_i_fu_560_p1 - zext_ln27_fu_486_p1);

assign multi_radix_oct_loser_64_temp0_52_address0 = grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_address0;

assign multi_radix_oct_loser_64_temp0_52_ce0 = grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_ce0;

assign multi_radix_oct_loser_64_temp0_52_d0 = grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_d0;

assign multi_radix_oct_loser_64_temp0_52_we0 = grp_radix_sort_oct_batch_53_1_Pipeline_output_bucket_fu_291_multi_radix_oct_loser_64_temp0_52_we0;

assign p_shl_cast_i_fu_560_p1 = p_shl_i_fu_553_p3;

assign p_shl_i_fu_553_p3 = {{i_29_reg_871}, {2'd0}};

assign zext_ln27_fu_486_p1 = i_29_reg_871;

endmodule //multi_radix_oct_loser_64_radix_sort_oct_batch_53_1
