// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module multi_radix_oct_kmerge_radix_sort_oct_batch_19_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_18_address0,
        input_18_ce0,
        input_18_q0,
        multi_radix_oct_kmerge_temp0_18_address0,
        multi_radix_oct_kmerge_temp0_18_ce0,
        multi_radix_oct_kmerge_temp0_18_we0,
        multi_radix_oct_kmerge_temp0_18_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [16:0] input_18_address0;
output   input_18_ce0;
input  [31:0] input_18_q0;
output  [16:0] multi_radix_oct_kmerge_temp0_18_address0;
output   multi_radix_oct_kmerge_temp0_18_ce0;
output   multi_radix_oct_kmerge_temp0_18_we0;
output  [31:0] multi_radix_oct_kmerge_temp0_18_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] i_105_reg_871;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln27_fu_383_p2;
wire  signed [17:0] grp_fu_571_p2;
reg   [17:0] mul_ln41_reg_986;
wire    ap_CS_fsm_state8;
wire   [6:0] mul_i_fu_564_p2;
reg   [6:0] mul_i_reg_991;
wire  signed [17:0] grp_fu_578_p2;
reg   [17:0] mul_ln43_reg_996;
reg   [17:0] bucket_address0;
reg    bucket_ce0;
reg    bucket_we0;
reg   [31:0] bucket_d0;
wire   [31:0] bucket_q0;
reg    bucket_ce1;
wire   [31:0] bucket_q1;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_done;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_idle;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_ready;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3803_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3803_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3802_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3802_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3801_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3801_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3800_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3800_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3799_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3799_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3798_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3798_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3797_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3797_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_out_ap_vld;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_done;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_idle;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_ready;
wire   [17:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_address0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_ce0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_we0;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_d0;
wire   [16:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_input_18_address0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_input_18_ce0;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3819_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3819_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3818_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3818_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3817_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3817_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3816_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3816_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3815_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3815_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3814_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3814_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3813_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3813_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3812_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3812_out_o_ap_vld;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_idle;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_ready;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3844_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3844_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3843_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3843_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3842_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3842_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3841_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3841_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3840_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3840_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3839_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3839_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3838_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3838_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3837_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3837_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1731_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1731_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1730_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1730_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1729_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1729_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1728_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1728_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1727_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1727_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1726_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1726_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1725_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1725_out_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1724_out;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1724_out_ap_vld;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_done;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_idle;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_ready;
wire   [17:0] grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_bucket_address0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_bucket_ce0;
wire   [16:0] grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_address0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_ce0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_we0;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_d0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_done;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_idle;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_ready;
wire   [17:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_address0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_ce0;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_we0;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_d0;
wire   [17:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_address1;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_ce1;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3860_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3860_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3859_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3859_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3858_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3858_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3857_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3857_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3856_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3856_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3855_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3855_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3854_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3854_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3853_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3853_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1740_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1740_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1739_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1739_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1738_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1738_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1737_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1737_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1736_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1736_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1735_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1735_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1734_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1734_out_o_ap_vld;
wire   [31:0] grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1733_out_o;
wire    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1733_out_o_ap_vld;
reg    grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start_reg;
reg    ap_block_state1_ignore_call44;
wire    ap_CS_fsm_state2;
reg    grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] bucket_sizes_1106_fu_116;
reg   [31:0] bucket_sizes_1105_fu_112;
reg   [31:0] bucket_sizes_1104_fu_108;
reg   [31:0] bucket_sizes_1103_fu_104;
reg   [31:0] bucket_sizes_1102_fu_100;
reg   [31:0] bucket_sizes_1101_fu_96;
reg   [31:0] bucket_sizes_1100_fu_92;
reg   [31:0] bucket_sizes_fu_88;
reg    grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [31:0] bucket_pointer_954_fu_84;
reg   [31:0] bucket_pointer_953_fu_80;
reg   [31:0] bucket_pointer_952_fu_76;
reg   [31:0] bucket_pointer_951_fu_72;
reg   [31:0] bucket_pointer_950_fu_68;
reg   [31:0] bucket_pointer_949_fu_64;
reg   [31:0] bucket_pointer_948_fu_60;
reg   [31:0] bucket_pointer_fu_56;
reg   [3:0] i_fu_48;
wire   [3:0] i_106_fu_389_p2;
reg    ap_block_state1;
reg   [31:0] bucket_num_fu_52;
wire   [31:0] bucket_num_53_fu_462_p2;
wire   [5:0] p_shl_i_fu_553_p3;
wire   [6:0] p_shl_cast_i_fu_560_p1;
wire   [6:0] zext_ln27_fu_486_p1;
wire  signed [17:0] grp_fu_571_p0;
wire   [16:0] grp_fu_571_p1;
wire  signed [17:0] grp_fu_578_p0;
wire   [16:0] grp_fu_578_p1;
reg    grp_fu_571_ce;
wire    ap_CS_fsm_state7;
reg    grp_fu_578_ce;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start_reg = 1'b0;
#0 grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start_reg = 1'b0;
end

multi_radix_oct_kmerge_radix_sort_oct_batch_19_1_bucket_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 156250 ),
    .AddressWidth( 18 ))
bucket_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bucket_address0),
    .ce0(bucket_ce0),
    .we0(bucket_we0),
    .d0(bucket_d0),
    .q0(bucket_q0),
    .address1(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_address1),
    .ce1(bucket_ce1),
    .q1(bucket_q1)
);

multi_radix_oct_kmerge_radix_sort_oct_batch_19_1_Pipeline_1 grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start),
    .ap_done(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_ready),
    .bucket_sizes_3803_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3803_out),
    .bucket_sizes_3803_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3803_out_ap_vld),
    .bucket_sizes_3802_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3802_out),
    .bucket_sizes_3802_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3802_out_ap_vld),
    .bucket_sizes_3801_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3801_out),
    .bucket_sizes_3801_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3801_out_ap_vld),
    .bucket_sizes_3800_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3800_out),
    .bucket_sizes_3800_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3800_out_ap_vld),
    .bucket_sizes_3799_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3799_out),
    .bucket_sizes_3799_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3799_out_ap_vld),
    .bucket_sizes_3798_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3798_out),
    .bucket_sizes_3798_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3798_out_ap_vld),
    .bucket_sizes_3797_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3797_out),
    .bucket_sizes_3797_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3797_out_ap_vld),
    .bucket_sizes_out(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_out),
    .bucket_sizes_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_out_ap_vld)
);

multi_radix_oct_kmerge_radix_sort_oct_batch_19_1_Pipeline_initialization grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start),
    .ap_done(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_ready),
    .bucket_sizes_3803_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3803_out),
    .bucket_sizes_3802_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3802_out),
    .bucket_sizes_3801_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3801_out),
    .bucket_sizes_3800_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3800_out),
    .bucket_sizes_3799_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3799_out),
    .bucket_sizes_3798_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3798_out),
    .bucket_sizes_3797_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_3797_out),
    .bucket_sizes_reload(grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_bucket_sizes_out),
    .bucket_address0(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_address0),
    .bucket_ce0(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_ce0),
    .bucket_we0(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_we0),
    .bucket_d0(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_d0),
    .input_18_address0(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_input_18_address0),
    .input_18_ce0(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_input_18_ce0),
    .input_18_q0(input_18_q0),
    .bucket_sizes_3819_out_i(bucket_sizes_1106_fu_116),
    .bucket_sizes_3819_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3819_out_o),
    .bucket_sizes_3819_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3819_out_o_ap_vld),
    .bucket_sizes_3818_out_i(bucket_sizes_1105_fu_112),
    .bucket_sizes_3818_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3818_out_o),
    .bucket_sizes_3818_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3818_out_o_ap_vld),
    .bucket_sizes_3817_out_i(bucket_sizes_1104_fu_108),
    .bucket_sizes_3817_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3817_out_o),
    .bucket_sizes_3817_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3817_out_o_ap_vld),
    .bucket_sizes_3816_out_i(bucket_sizes_1103_fu_104),
    .bucket_sizes_3816_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3816_out_o),
    .bucket_sizes_3816_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3816_out_o_ap_vld),
    .bucket_sizes_3815_out_i(bucket_sizes_1102_fu_100),
    .bucket_sizes_3815_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3815_out_o),
    .bucket_sizes_3815_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3815_out_o_ap_vld),
    .bucket_sizes_3814_out_i(bucket_sizes_1101_fu_96),
    .bucket_sizes_3814_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3814_out_o),
    .bucket_sizes_3814_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3814_out_o_ap_vld),
    .bucket_sizes_3813_out_i(bucket_sizes_1100_fu_92),
    .bucket_sizes_3813_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3813_out_o),
    .bucket_sizes_3813_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3813_out_o_ap_vld),
    .bucket_sizes_3812_out_i(bucket_sizes_fu_88),
    .bucket_sizes_3812_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3812_out_o),
    .bucket_sizes_3812_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3812_out_o_ap_vld)
);

multi_radix_oct_kmerge_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start),
    .ap_done(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_ready),
    .bucket_sizes_3836(bucket_sizes_1106_fu_116),
    .bucket_sizes_3835(bucket_sizes_1105_fu_112),
    .bucket_sizes_3834(bucket_sizes_1104_fu_108),
    .bucket_sizes_3833(bucket_sizes_1103_fu_104),
    .bucket_sizes_3832(bucket_sizes_1102_fu_100),
    .bucket_sizes_3831(bucket_sizes_1101_fu_96),
    .bucket_sizes_3830(bucket_sizes_1100_fu_92),
    .bucket_sizes_3829(bucket_sizes_fu_88),
    .bucket_pointer_1723(bucket_pointer_954_fu_84),
    .bucket_pointer_1722(bucket_pointer_953_fu_80),
    .bucket_pointer_1721(bucket_pointer_952_fu_76),
    .bucket_pointer_1720(bucket_pointer_951_fu_72),
    .bucket_pointer_1719(bucket_pointer_950_fu_68),
    .bucket_pointer_1718(bucket_pointer_949_fu_64),
    .bucket_pointer_1717(bucket_pointer_948_fu_60),
    .bucket_pointer(bucket_pointer_fu_56),
    .bucket_sizes_3844_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3844_out),
    .bucket_sizes_3844_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3844_out_ap_vld),
    .bucket_sizes_3843_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3843_out),
    .bucket_sizes_3843_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3843_out_ap_vld),
    .bucket_sizes_3842_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3842_out),
    .bucket_sizes_3842_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3842_out_ap_vld),
    .bucket_sizes_3841_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3841_out),
    .bucket_sizes_3841_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3841_out_ap_vld),
    .bucket_sizes_3840_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3840_out),
    .bucket_sizes_3840_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3840_out_ap_vld),
    .bucket_sizes_3839_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3839_out),
    .bucket_sizes_3839_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3839_out_ap_vld),
    .bucket_sizes_3838_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3838_out),
    .bucket_sizes_3838_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3838_out_ap_vld),
    .bucket_sizes_3837_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3837_out),
    .bucket_sizes_3837_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3837_out_ap_vld),
    .bucket_pointer_1731_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1731_out),
    .bucket_pointer_1731_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1731_out_ap_vld),
    .bucket_pointer_1730_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1730_out),
    .bucket_pointer_1730_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1730_out_ap_vld),
    .bucket_pointer_1729_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1729_out),
    .bucket_pointer_1729_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1729_out_ap_vld),
    .bucket_pointer_1728_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1728_out),
    .bucket_pointer_1728_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1728_out_ap_vld),
    .bucket_pointer_1727_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1727_out),
    .bucket_pointer_1727_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1727_out_ap_vld),
    .bucket_pointer_1726_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1726_out),
    .bucket_pointer_1726_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1726_out_ap_vld),
    .bucket_pointer_1725_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1725_out),
    .bucket_pointer_1725_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1725_out_ap_vld),
    .bucket_pointer_1724_out(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1724_out),
    .bucket_pointer_1724_out_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1724_out_ap_vld)
);

multi_radix_oct_kmerge_radix_sort_oct_batch_19_1_Pipeline_output_bucket grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start),
    .ap_done(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_ready),
    .bucket_address0(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_bucket_address0),
    .bucket_ce0(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_bucket_ce0),
    .bucket_q0(bucket_q0),
    .multi_radix_oct_kmerge_temp0_18_address0(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_address0),
    .multi_radix_oct_kmerge_temp0_18_ce0(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_ce0),
    .multi_radix_oct_kmerge_temp0_18_we0(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_we0),
    .multi_radix_oct_kmerge_temp0_18_d0(grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_d0)
);

multi_radix_oct_kmerge_radix_sort_oct_batch_19_1_Pipeline_input_bucket grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start),
    .ap_done(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_done),
    .ap_idle(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_idle),
    .ap_ready(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_ready),
    .bucket_sizes_3844_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3844_out),
    .bucket_sizes_3843_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3843_out),
    .bucket_sizes_3842_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3842_out),
    .bucket_sizes_3841_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3841_out),
    .bucket_sizes_3840_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3840_out),
    .bucket_sizes_3839_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3839_out),
    .bucket_sizes_3838_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3838_out),
    .bucket_sizes_3837_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_sizes_3837_out),
    .bucket_pointer_1731_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1731_out),
    .bucket_pointer_1730_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1730_out),
    .bucket_pointer_1729_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1729_out),
    .bucket_pointer_1728_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1728_out),
    .bucket_pointer_1727_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1727_out),
    .bucket_pointer_1726_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1726_out),
    .bucket_pointer_1725_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1725_out),
    .bucket_pointer_1724_reload(grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_bucket_pointer_1724_out),
    .mul_ln41(mul_ln41_reg_986),
    .bucket_address0(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_address0),
    .bucket_ce0(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_ce0),
    .bucket_we0(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_we0),
    .bucket_d0(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_d0),
    .bucket_address1(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_address1),
    .bucket_ce1(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_ce1),
    .bucket_q1(bucket_q1),
    .mul_cast_i(mul_i_reg_991),
    .mul_ln43(mul_ln43_reg_996),
    .bucket_sizes_3860_out_i(bucket_sizes_1106_fu_116),
    .bucket_sizes_3860_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3860_out_o),
    .bucket_sizes_3860_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3860_out_o_ap_vld),
    .bucket_sizes_3859_out_i(bucket_sizes_1105_fu_112),
    .bucket_sizes_3859_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3859_out_o),
    .bucket_sizes_3859_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3859_out_o_ap_vld),
    .bucket_sizes_3858_out_i(bucket_sizes_1104_fu_108),
    .bucket_sizes_3858_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3858_out_o),
    .bucket_sizes_3858_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3858_out_o_ap_vld),
    .bucket_sizes_3857_out_i(bucket_sizes_1103_fu_104),
    .bucket_sizes_3857_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3857_out_o),
    .bucket_sizes_3857_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3857_out_o_ap_vld),
    .bucket_sizes_3856_out_i(bucket_sizes_1102_fu_100),
    .bucket_sizes_3856_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3856_out_o),
    .bucket_sizes_3856_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3856_out_o_ap_vld),
    .bucket_sizes_3855_out_i(bucket_sizes_1101_fu_96),
    .bucket_sizes_3855_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3855_out_o),
    .bucket_sizes_3855_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3855_out_o_ap_vld),
    .bucket_sizes_3854_out_i(bucket_sizes_1100_fu_92),
    .bucket_sizes_3854_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3854_out_o),
    .bucket_sizes_3854_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3854_out_o_ap_vld),
    .bucket_sizes_3853_out_i(bucket_sizes_fu_88),
    .bucket_sizes_3853_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3853_out_o),
    .bucket_sizes_3853_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3853_out_o_ap_vld),
    .bucket_pointer_1740_out_i(bucket_pointer_954_fu_84),
    .bucket_pointer_1740_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1740_out_o),
    .bucket_pointer_1740_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1740_out_o_ap_vld),
    .bucket_pointer_1739_out_i(bucket_pointer_953_fu_80),
    .bucket_pointer_1739_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1739_out_o),
    .bucket_pointer_1739_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1739_out_o_ap_vld),
    .bucket_pointer_1738_out_i(bucket_pointer_952_fu_76),
    .bucket_pointer_1738_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1738_out_o),
    .bucket_pointer_1738_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1738_out_o_ap_vld),
    .bucket_pointer_1737_out_i(bucket_pointer_951_fu_72),
    .bucket_pointer_1737_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1737_out_o),
    .bucket_pointer_1737_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1737_out_o_ap_vld),
    .bucket_pointer_1736_out_i(bucket_pointer_950_fu_68),
    .bucket_pointer_1736_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1736_out_o),
    .bucket_pointer_1736_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1736_out_o_ap_vld),
    .bucket_pointer_1735_out_i(bucket_pointer_949_fu_64),
    .bucket_pointer_1735_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1735_out_o),
    .bucket_pointer_1735_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1735_out_o_ap_vld),
    .bucket_pointer_1734_out_i(bucket_pointer_948_fu_60),
    .bucket_pointer_1734_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1734_out_o),
    .bucket_pointer_1734_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1734_out_o_ap_vld),
    .bucket_pointer_1733_out_i(bucket_pointer_fu_56),
    .bucket_pointer_1733_out_o(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1733_out_o),
    .bucket_pointer_1733_out_o_ap_vld(grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1733_out_o_ap_vld)
);

multi_radix_oct_kmerge_mul_mul_18s_17ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mul_mul_18s_17ns_18_4_1_U1993(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_571_p0),
    .din1(grp_fu_571_p1),
    .ce(grp_fu_571_ce),
    .dout(grp_fu_571_p2)
);

multi_radix_oct_kmerge_mul_mul_18s_17ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mul_mul_18s_17ns_18_4_1_U1994(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_578_p0),
    .din1(grp_fu_578_p1),
    .ce(grp_fu_578_ce),
    .dout(grp_fu_578_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln27_fu_383_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln27_fu_383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start_reg <= 1'b1;
        end else if ((grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_ready == 1'b1)) begin
            grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_num_fu_52 <= 32'd0;
    end else if (((icmp_ln27_fu_383_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        bucket_num_fu_52 <= bucket_num_53_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3854_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_1100_fu_92 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3854_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3813_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_1100_fu_92 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3813_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3855_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_1101_fu_96 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3855_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3814_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_1101_fu_96 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3814_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3856_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_1102_fu_100 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3856_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3815_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_1102_fu_100 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3815_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3857_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_1103_fu_104 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3857_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3816_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_1103_fu_104 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3816_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3858_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_1104_fu_108 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3858_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3817_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_1104_fu_108 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3817_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3859_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_1105_fu_112 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3859_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3818_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_1105_fu_112 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3818_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3860_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_1106_fu_116 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3860_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3819_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_1106_fu_116 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3819_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3853_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_sizes_fu_88 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_sizes_3853_out_o;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3812_out_o_ap_vld == 1'b1))) begin
        bucket_sizes_fu_88 <= grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_sizes_3812_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_48 <= 4'd0;
    end else if (((icmp_ln27_fu_383_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        i_fu_48 <= i_106_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1734_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_948_fu_60 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1734_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1735_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_949_fu_64 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1735_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1736_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_950_fu_68 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1736_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1737_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_951_fu_72 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1737_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1738_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_952_fu_76 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1738_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1739_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_953_fu_80 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1739_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1740_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_954_fu_84 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1740_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1733_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        bucket_pointer_fu_56 <= grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_pointer_1733_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_105_reg_871 <= i_fu_48;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul_i_reg_991 <= mul_i_fu_564_p2;
        mul_ln41_reg_986 <= grp_fu_571_p2;
        mul_ln43_reg_996 <= grp_fu_578_p2;
    end
end

always @ (*) begin
    if ((grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_address0 = grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        bucket_address0 = grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_bucket_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_address0 = grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_address0;
    end else begin
        bucket_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_ce0 = grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        bucket_ce0 = grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_bucket_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_ce0 = grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_ce0;
    end else begin
        bucket_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_ce1 = grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_ce1;
    end else begin
        bucket_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_d0 = grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_d0 = grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_d0;
    end else begin
        bucket_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bucket_we0 = grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_bucket_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bucket_we0 = grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_bucket_we0;
    end else begin
        bucket_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b1)))) begin
        grp_fu_571_ce = 1'b1;
    end else begin
        grp_fu_571_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b1)))) begin
        grp_fu_578_ce = 1'b1;
    end else begin
        grp_fu_578_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln27_fu_383_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call44 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bucket_num_53_fu_462_p2 = (32'd1 - bucket_num_fu_52);

assign grp_fu_571_p0 = bucket_num_53_fu_462_p2[17:0];

assign grp_fu_571_p1 = 18'd78125;

assign grp_fu_578_p0 = bucket_num_fu_52[17:0];

assign grp_fu_578_p1 = 18'd78125;

assign grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start = grp_radix_sort_oct_batch_19_1_Pipeline_1_fu_220_ap_start_reg;

assign grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start = grp_radix_sort_oct_batch_19_1_Pipeline_bucket_pointer_initialization_fu_255_ap_start_reg;

assign grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start = grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_ap_start_reg;

assign grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start = grp_radix_sort_oct_batch_19_1_Pipeline_input_bucket_fu_298_ap_start_reg;

assign grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start = grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_ap_start_reg;

assign i_106_fu_389_p2 = (i_fu_48 + 4'd1);

assign icmp_ln27_fu_383_p2 = ((i_fu_48 == 4'd11) ? 1'b1 : 1'b0);

assign input_18_address0 = grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_input_18_address0;

assign input_18_ce0 = grp_radix_sort_oct_batch_19_1_Pipeline_initialization_fu_232_input_18_ce0;

assign mul_i_fu_564_p2 = (p_shl_cast_i_fu_560_p1 - zext_ln27_fu_486_p1);

assign multi_radix_oct_kmerge_temp0_18_address0 = grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_address0;

assign multi_radix_oct_kmerge_temp0_18_ce0 = grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_ce0;

assign multi_radix_oct_kmerge_temp0_18_d0 = grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_d0;

assign multi_radix_oct_kmerge_temp0_18_we0 = grp_radix_sort_oct_batch_19_1_Pipeline_output_bucket_fu_291_multi_radix_oct_kmerge_temp0_18_we0;

assign p_shl_cast_i_fu_560_p1 = p_shl_i_fu_553_p3;

assign p_shl_i_fu_553_p3 = {{i_105_reg_871}, {2'd0}};

assign zext_ln27_fu_486_p1 = i_105_reg_871;

endmodule //multi_radix_oct_kmerge_radix_sort_oct_batch_19_1
