// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sort_top_64_radix_sort_unified_bucket_pingpong_60_1_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bucket_sizes_885_out,
        bucket_sizes_885_out_ap_vld,
        bucket_sizes_884_out,
        bucket_sizes_884_out_ap_vld,
        bucket_sizes_883_out,
        bucket_sizes_883_out_ap_vld,
        bucket_sizes_882_out,
        bucket_sizes_882_out_ap_vld,
        bucket_sizes_881_out,
        bucket_sizes_881_out_ap_vld,
        bucket_sizes_880_out,
        bucket_sizes_880_out_ap_vld,
        bucket_sizes_879_out,
        bucket_sizes_879_out_ap_vld,
        bucket_sizes_878_out,
        bucket_sizes_878_out_ap_vld,
        bucket_sizes_877_out,
        bucket_sizes_877_out_ap_vld,
        bucket_sizes_876_out,
        bucket_sizes_876_out_ap_vld,
        bucket_sizes_875_out,
        bucket_sizes_875_out_ap_vld,
        bucket_sizes_874_out,
        bucket_sizes_874_out_ap_vld,
        bucket_sizes_873_out,
        bucket_sizes_873_out_ap_vld,
        bucket_sizes_872_out,
        bucket_sizes_872_out_ap_vld,
        bucket_sizes_871_out,
        bucket_sizes_871_out_ap_vld,
        bucket_sizes_out,
        bucket_sizes_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] bucket_sizes_885_out;
output   bucket_sizes_885_out_ap_vld;
output  [31:0] bucket_sizes_884_out;
output   bucket_sizes_884_out_ap_vld;
output  [31:0] bucket_sizes_883_out;
output   bucket_sizes_883_out_ap_vld;
output  [31:0] bucket_sizes_882_out;
output   bucket_sizes_882_out_ap_vld;
output  [31:0] bucket_sizes_881_out;
output   bucket_sizes_881_out_ap_vld;
output  [31:0] bucket_sizes_880_out;
output   bucket_sizes_880_out_ap_vld;
output  [31:0] bucket_sizes_879_out;
output   bucket_sizes_879_out_ap_vld;
output  [31:0] bucket_sizes_878_out;
output   bucket_sizes_878_out_ap_vld;
output  [31:0] bucket_sizes_877_out;
output   bucket_sizes_877_out_ap_vld;
output  [31:0] bucket_sizes_876_out;
output   bucket_sizes_876_out_ap_vld;
output  [31:0] bucket_sizes_875_out;
output   bucket_sizes_875_out_ap_vld;
output  [31:0] bucket_sizes_874_out;
output   bucket_sizes_874_out_ap_vld;
output  [31:0] bucket_sizes_873_out;
output   bucket_sizes_873_out_ap_vld;
output  [31:0] bucket_sizes_872_out;
output   bucket_sizes_872_out_ap_vld;
output  [31:0] bucket_sizes_871_out;
output   bucket_sizes_871_out_ap_vld;
output  [31:0] bucket_sizes_out;
output   bucket_sizes_out_ap_vld;

reg ap_idle;
reg bucket_sizes_885_out_ap_vld;
reg bucket_sizes_884_out_ap_vld;
reg bucket_sizes_883_out_ap_vld;
reg bucket_sizes_882_out_ap_vld;
reg bucket_sizes_881_out_ap_vld;
reg bucket_sizes_880_out_ap_vld;
reg bucket_sizes_879_out_ap_vld;
reg bucket_sizes_878_out_ap_vld;
reg bucket_sizes_877_out_ap_vld;
reg bucket_sizes_876_out_ap_vld;
reg bucket_sizes_875_out_ap_vld;
reg bucket_sizes_874_out_ap_vld;
reg bucket_sizes_873_out_ap_vld;
reg bucket_sizes_872_out_ap_vld;
reg bucket_sizes_871_out_ap_vld;
reg bucket_sizes_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] exitcond116_fu_272_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] empty_fu_84;
wire   [4:0] empty_102_fu_278_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_p_load;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

sort_top_64_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond116_fu_272_p2 == 1'd0)) begin
            empty_fu_84 <= empty_102_fu_278_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_84 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_p_load = 5'd0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_84;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_871_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_871_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_872_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_872_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_873_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_873_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_874_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_874_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_875_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_875_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_876_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_876_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_877_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_877_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_878_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_878_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_879_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_879_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_880_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_880_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_881_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_881_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_882_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_882_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_883_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_883_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_884_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_884_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_885_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_885_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond116_fu_272_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        bucket_sizes_out_ap_vld = 1'b1;
    end else begin
        bucket_sizes_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bucket_sizes_871_out = 32'd0;

assign bucket_sizes_872_out = 32'd0;

assign bucket_sizes_873_out = 32'd0;

assign bucket_sizes_874_out = 32'd0;

assign bucket_sizes_875_out = 32'd0;

assign bucket_sizes_876_out = 32'd0;

assign bucket_sizes_877_out = 32'd0;

assign bucket_sizes_878_out = 32'd0;

assign bucket_sizes_879_out = 32'd0;

assign bucket_sizes_880_out = 32'd0;

assign bucket_sizes_881_out = 32'd0;

assign bucket_sizes_882_out = 32'd0;

assign bucket_sizes_883_out = 32'd0;

assign bucket_sizes_884_out = 32'd0;

assign bucket_sizes_885_out = 32'd0;

assign bucket_sizes_out = 32'd0;

assign empty_102_fu_278_p2 = (ap_sig_allocacmp_p_load + 5'd1);

assign exitcond116_fu_272_p2 = ((ap_sig_allocacmp_p_load == 5'd16) ? 1'b1 : 1'b0);

endmodule //sort_top_64_radix_sort_unified_bucket_pingpong_60_1_Pipeline_1
