set SynModuleInfo {
  {SRCNAME radix_sort_seperate_bucket_parallel_Pipeline_1 MODELNAME radix_sort_seperate_bucket_parallel_Pipeline_1 RTLNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_1
    SUBMODULES {
      {MODELNAME radix_sort_seperate_bucket_parallel_flow_control_loop_pipe_sequential_init RTLNAME radix_sort_seperate_bucket_parallel_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME radix_sort_seperate_bucket_parallel_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME radix_sort_seperate_bucket_parallel_Pipeline_2 MODELNAME radix_sort_seperate_bucket_parallel_Pipeline_2 RTLNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_2}
  {SRCNAME radix_sort_seperate_bucket_parallel_Pipeline_initialization MODELNAME radix_sort_seperate_bucket_parallel_Pipeline_initialization RTLNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_initialization}
  {SRCNAME input_bucket.1.1 MODELNAME input_bucket_1_1 RTLNAME radix_sort_seperate_bucket_parallel_input_bucket_1_1
    SUBMODULES {
      {MODELNAME radix_sort_seperate_bucket_parallel_mac_muladd_4ns_5ns_9ns_9_4_1 RTLNAME radix_sort_seperate_bucket_parallel_mac_muladd_4ns_5ns_9ns_9_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME input_bucket_parallel.1 MODELNAME input_bucket_parallel_1 RTLNAME radix_sort_seperate_bucket_parallel_input_bucket_parallel_1}
  {SRCNAME radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_135_1 MODELNAME radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_135_1 RTLNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_135_1}
  {SRCNAME radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_140_2 MODELNAME radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_140_2 RTLNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_140_2
    SUBMODULES {
      {MODELNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_140_2_bucket2_RAM_AUTbkb RTLNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_VITIS_LOOP_140_2_bucket2_RAM_AUTbkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME radix_sort_seperate_bucket_parallel_Pipeline_clear_bucket_pointer MODELNAME radix_sort_seperate_bucket_parallel_Pipeline_clear_bucket_pointer RTLNAME radix_sort_seperate_bucket_parallel_radix_sort_seperate_bucket_parallel_Pipeline_clear_bucket_pointer}
  {SRCNAME radix_sort_seperate_bucket_parallel MODELNAME radix_sort_seperate_bucket_parallel RTLNAME radix_sort_seperate_bucket_parallel IS_TOP 1
    SUBMODULES {
      {MODELNAME radix_sort_seperate_bucket_parallel_bucket1_RAM_AUTO_1R1W RTLNAME radix_sort_seperate_bucket_parallel_bucket1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME radix_sort_seperate_bucket_parallel_bucket_pointer1_RAM_AUTO_1R1W RTLNAME radix_sort_seperate_bucket_parallel_bucket_pointer1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME radix_sort_seperate_bucket_parallel_bucket_pointer2_RAM_AUTO_1R1W RTLNAME radix_sort_seperate_bucket_parallel_bucket_pointer2_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
