set SynModuleInfo {
  {SRCNAME single_heap_sort_Pipeline_VITIS_LOOP_44_1 MODELNAME single_heap_sort_Pipeline_VITIS_LOOP_44_1 RTLNAME single_heap_sort_single_heap_sort_Pipeline_VITIS_LOOP_44_1
    SUBMODULES {
      {MODELNAME single_heap_sort_flow_control_loop_pipe_sequential_init RTLNAME single_heap_sort_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME single_heap_sort_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME single_heap_sort_Pipeline_VITIS_LOOP_44_11 MODELNAME single_heap_sort_Pipeline_VITIS_LOOP_44_11 RTLNAME single_heap_sort_single_heap_sort_Pipeline_VITIS_LOOP_44_11}
  {SRCNAME single_heap_sort_Pipeline_output_data MODELNAME single_heap_sort_Pipeline_output_data RTLNAME single_heap_sort_single_heap_sort_Pipeline_output_data}
  {SRCNAME single_heap_sort MODELNAME single_heap_sort RTLNAME single_heap_sort IS_TOP 1}
}
