set SynModuleInfo {
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_1 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_1 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_1
    SUBMODULES {
      {MODELNAME radix_sort_separate_bucket_parallel_5_flow_control_loop_pipe_sequential_init RTLNAME radix_sort_separate_bucket_parallel_5_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME radix_sort_separate_bucket_parallel_5_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_2 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_2 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_2}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_3 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_3 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_3}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_4 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_4 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_4}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_initialization MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_initialization RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_initialization}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_inner_loop_initialization MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_inner_loop_initialization RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_inner_loop_initialization}
  {SRCNAME input_bucket_5.1 MODELNAME input_bucket_5_1 RTLNAME radix_sort_separate_bucket_parallel_5_input_bucket_5_1}
  {SRCNAME input_bucket_5.2 MODELNAME input_bucket_5_2 RTLNAME radix_sort_separate_bucket_parallel_5_input_bucket_5_2}
  {SRCNAME input_bucket_5.3 MODELNAME input_bucket_5_3 RTLNAME radix_sort_separate_bucket_parallel_5_input_bucket_5_3}
  {SRCNAME input_bucket_parallel_5 MODELNAME input_bucket_parallel_5 RTLNAME radix_sort_separate_bucket_parallel_5_input_bucket_parallel_5}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_138_1 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_138_1 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_138_1}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_143_2 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_143_2 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_143_2}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_148_3 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_148_3 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_148_3}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_153_4 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_153_4 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_153_4
    SUBMODULES {
      {MODELNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_153_4_bucket3_RAM_Abkb RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_153_4_bucket3_RAM_Abkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_158_5 MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_158_5 RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_VITIS_LOOP_158_5}
  {SRCNAME radix_sort_separate_bucket_parallel_5_Pipeline_clear_bucket_pointer MODELNAME radix_sort_separate_bucket_parallel_5_Pipeline_clear_bucket_pointer RTLNAME radix_sort_separate_bucket_parallel_5_radix_sort_separate_bucket_parallel_5_Pipeline_clear_bucket_pointer}
  {SRCNAME radix_sort_separate_bucket_parallel_5 MODELNAME radix_sort_separate_bucket_parallel_5 RTLNAME radix_sort_separate_bucket_parallel_5 IS_TOP 1
    SUBMODULES {
      {MODELNAME radix_sort_separate_bucket_parallel_5_bucket0_RAM_AUTO_1R1W RTLNAME radix_sort_separate_bucket_parallel_5_bucket0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME radix_sort_separate_bucket_parallel_5_bucket_pointer0_RAM_AUTO_1R1W RTLNAME radix_sort_separate_bucket_parallel_5_bucket_pointer0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME radix_sort_separate_bucket_parallel_5_bucket_pointer3_RAM_AUTO_1R1W RTLNAME radix_sort_separate_bucket_parallel_5_bucket_pointer3_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME radix_sort_separate_bucket_parallel_5_sorted_data0_RAM_AUTO_1R1W RTLNAME radix_sort_separate_bucket_parallel_5_sorted_data0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
