-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sort_top_radix_sort_unified_bucket_1_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    input_r_ce1 : OUT STD_LOGIC;
    input_r_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    sorted_data_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
    sorted_data_ce0 : OUT STD_LOGIC;
    sorted_data_we0 : OUT STD_LOGIC;
    sorted_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    sorted_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of sort_top_radix_sort_unified_bucket_1_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_17_fu_126_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_17_reg_153 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln24_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_fu_135_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_reg_158 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal bucket_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal bucket_ce0 : STD_LOGIC;
    signal bucket_we0 : STD_LOGIC;
    signal bucket_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bucket_pointer_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal bucket_pointer_ce0 : STD_LOGIC;
    signal bucket_pointer_we0 : STD_LOGIC;
    signal bucket_pointer_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bucket_pointer_ce1 : STD_LOGIC;
    signal bucket_pointer_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bucket_sizes_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal bucket_sizes_ce0 : STD_LOGIC;
    signal bucket_sizes_we0 : STD_LOGIC;
    signal bucket_sizes_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bucket_sizes_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bucket_sizes_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal bucket_sizes_ce1 : STD_LOGIC;
    signal bucket_sizes_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_done : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_idle : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_ready : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_done : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_idle : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_ready : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_input_r_address1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_input_r_ce1 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce1 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_done : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_idle : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_ready : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_done : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_idle : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_ready : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce1 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce1 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_done : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_idle : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_ready : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_address0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_ce0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_we0 : STD_LOGIC;
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call7 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal i_fu_52 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_2_fu_120_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sort_top_radix_sort_unified_bucket_1_2_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bucket_sizes_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_sizes_ce0 : OUT STD_LOGIC;
        bucket_sizes_we0 : OUT STD_LOGIC;
        bucket_sizes_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_top_radix_sort_unified_bucket_1_2_Pipeline_initialization IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        input_r_ce1 : OUT STD_LOGIC;
        input_r_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        sorted_data_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        sorted_data_ce0 : OUT STD_LOGIC;
        sorted_data_we0 : OUT STD_LOGIC;
        sorted_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        bucket_sizes_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_sizes_ce0 : OUT STD_LOGIC;
        bucket_sizes_we0 : OUT STD_LOGIC;
        bucket_sizes_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        bucket_sizes_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_sizes_ce1 : OUT STD_LOGIC;
        bucket_sizes_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_top_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bucket_pointer_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_pointer_ce0 : OUT STD_LOGIC;
        bucket_pointer_we0 : OUT STD_LOGIC;
        bucket_pointer_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        bucket_sizes_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_sizes_ce0 : OUT STD_LOGIC;
        bucket_sizes_we0 : OUT STD_LOGIC;
        bucket_sizes_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        bucket_sizes_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_top_radix_sort_unified_bucket_1_2_Pipeline_input_bucket IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sorted_data_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        sorted_data_ce0 : OUT STD_LOGIC;
        sorted_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln39 : IN STD_LOGIC_VECTOR (4 downto 0);
        bucket_pointer_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_pointer_ce0 : OUT STD_LOGIC;
        bucket_pointer_we0 : OUT STD_LOGIC;
        bucket_pointer_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        bucket_pointer_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_pointer_ce1 : OUT STD_LOGIC;
        bucket_pointer_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        bucket_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        bucket_ce0 : OUT STD_LOGIC;
        bucket_we0 : OUT STD_LOGIC;
        bucket_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        bucket_sizes_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_sizes_ce0 : OUT STD_LOGIC;
        bucket_sizes_we0 : OUT STD_LOGIC;
        bucket_sizes_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        bucket_sizes_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        bucket_sizes_ce1 : OUT STD_LOGIC;
        bucket_sizes_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_top_radix_sort_unified_bucket_1_2_Pipeline_output_bucket IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bucket_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        bucket_ce0 : OUT STD_LOGIC;
        bucket_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        sorted_data_address0 : OUT STD_LOGIC_VECTOR (18 downto 0);
        sorted_data_ce0 : OUT STD_LOGIC;
        sorted_data_we0 : OUT STD_LOGIC;
        sorted_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_top_radix_sort_unified_bucket_1_2_bucket_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_top_radix_sort_unified_bucket_1_2_bucket_pointer_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sort_top_radix_sort_unified_bucket_1_2_bucket_sizes_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    bucket_U : component sort_top_radix_sort_unified_bucket_1_2_bucket_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 500000,
        AddressWidth => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => bucket_address0,
        ce0 => bucket_ce0,
        we0 => bucket_we0,
        d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_d0,
        q0 => bucket_q0);

    bucket_pointer_U : component sort_top_radix_sort_unified_bucket_1_2_bucket_pointer_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => bucket_pointer_address0,
        ce0 => bucket_pointer_ce0,
        we0 => bucket_pointer_we0,
        d0 => bucket_pointer_d0,
        address1 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_address1,
        ce1 => bucket_pointer_ce1,
        q1 => bucket_pointer_q1);

    bucket_sizes_U : component sort_top_radix_sort_unified_bucket_1_2_bucket_sizes_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => bucket_sizes_address0,
        ce0 => bucket_sizes_ce0,
        we0 => bucket_sizes_we0,
        d0 => bucket_sizes_d0,
        q0 => bucket_sizes_q0,
        address1 => bucket_sizes_address1,
        ce1 => bucket_sizes_ce1,
        q1 => bucket_sizes_q1);

    grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68 : component sort_top_radix_sort_unified_bucket_1_2_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start,
        ap_done => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_done,
        ap_idle => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_idle,
        ap_ready => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_ready,
        bucket_sizes_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_address0,
        bucket_sizes_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_ce0,
        bucket_sizes_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_we0,
        bucket_sizes_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_d0);

    grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74 : component sort_top_radix_sort_unified_bucket_1_2_Pipeline_initialization
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start,
        ap_done => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_done,
        ap_idle => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_idle,
        ap_ready => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_ready,
        input_r_address1 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_input_r_address1,
        input_r_ce1 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_input_r_ce1,
        input_r_q1 => input_r_q1,
        sorted_data_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_address0,
        sorted_data_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_ce0,
        sorted_data_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_we0,
        sorted_data_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_d0,
        bucket_sizes_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address0,
        bucket_sizes_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce0,
        bucket_sizes_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_we0,
        bucket_sizes_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_d0,
        bucket_sizes_address1 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address1,
        bucket_sizes_ce1 => grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce1,
        bucket_sizes_q1 => bucket_sizes_q1);

    grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83 : component sort_top_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start,
        ap_done => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_done,
        ap_idle => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_idle,
        ap_ready => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_ready,
        bucket_pointer_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_address0,
        bucket_pointer_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_ce0,
        bucket_pointer_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_we0,
        bucket_pointer_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_d0,
        bucket_sizes_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_address0,
        bucket_sizes_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_ce0,
        bucket_sizes_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_we0,
        bucket_sizes_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_d0,
        bucket_sizes_q0 => bucket_sizes_q0);

    grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89 : component sort_top_radix_sort_unified_bucket_1_2_Pipeline_input_bucket
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start,
        ap_done => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_done,
        ap_idle => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_idle,
        ap_ready => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_ready,
        sorted_data_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_address0,
        sorted_data_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_ce0,
        sorted_data_q0 => sorted_data_q0,
        zext_ln39 => mul_reg_158,
        bucket_pointer_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_address0,
        bucket_pointer_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce0,
        bucket_pointer_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_we0,
        bucket_pointer_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_d0,
        bucket_pointer_address1 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_address1,
        bucket_pointer_ce1 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce1,
        bucket_pointer_q1 => bucket_pointer_q1,
        bucket_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_address0,
        bucket_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_ce0,
        bucket_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_we0,
        bucket_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_d0,
        bucket_sizes_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address0,
        bucket_sizes_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce0,
        bucket_sizes_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_we0,
        bucket_sizes_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_d0,
        bucket_sizes_address1 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address1,
        bucket_sizes_ce1 => grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce1,
        bucket_sizes_q1 => bucket_sizes_q1);

    grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99 : component sort_top_radix_sort_unified_bucket_1_2_Pipeline_output_bucket
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start,
        ap_done => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_done,
        ap_idle => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_idle,
        ap_ready => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_ready,
        bucket_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_address0,
        bucket_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_ce0,
        bucket_q0 => bucket_q0,
        sorted_data_address0 => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_address0,
        sorted_data_ce0 => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_ce0,
        sorted_data_we0 => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_we0,
        sorted_data_d0 => grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln24_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln24_fu_114_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_ready = ap_const_logic_1)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_ready = ap_const_logic_1)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_ready = ap_const_logic_1)) then 
                    grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_52 <= ap_const_lv4_0;
            elsif (((icmp_ln24_fu_114_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_fu_52 <= i_2_fu_120_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_fu_114_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                empty_17_reg_153 <= empty_17_fu_126_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                    mul_reg_158(4 downto 2) <= mul_fu_135_p3(4 downto 2);
            end if;
        end if;
    end process;
    mul_reg_158(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, icmp_ln24_fu_114_p2, grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_done, grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_done, grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_done, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_done, grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln24_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_done)
    begin
        if ((grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_done)
    begin
        if ((grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_done)
    begin
        if ((grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_done)
    begin
        if ((grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_done)
    begin
        if ((grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call7_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call7 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, icmp_ln24_fu_114_p2)
    begin
        if (((icmp_ln24_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln24_fu_114_p2)
    begin
        if (((icmp_ln24_fu_114_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bucket_address0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_address0, grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_address0, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            bucket_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_address0;
        else 
            bucket_address0 <= "XXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    bucket_ce0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_ce0, grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_ce0, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            bucket_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_bucket_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_ce0;
        else 
            bucket_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    bucket_pointer_address0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_address0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_address0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_pointer_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_pointer_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_address0;
        else 
            bucket_pointer_address0 <= "XXXX";
        end if; 
    end process;


    bucket_pointer_ce0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_ce0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_pointer_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_pointer_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_ce0;
        else 
            bucket_pointer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    bucket_pointer_ce1_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_pointer_ce1 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_ce1;
        else 
            bucket_pointer_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    bucket_pointer_d0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_d0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_d0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_pointer_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_pointer_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_d0;
        else 
            bucket_pointer_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    bucket_pointer_we0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_we0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_we0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_pointer_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_pointer_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_pointer_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_pointer_we0;
        else 
            bucket_pointer_we0 <= ap_const_logic_0;
        end if; 
    end process;


    bucket_sizes_address0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_address0, grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address0, grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_address0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_sizes_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_sizes_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bucket_sizes_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bucket_sizes_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_address0;
        else 
            bucket_sizes_address0 <= "XXXX";
        end if; 
    end process;


    bucket_sizes_address1_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address1, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address1, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_sizes_address1 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bucket_sizes_address1 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_address1;
        else 
            bucket_sizes_address1 <= "XXXX";
        end if; 
    end process;


    bucket_sizes_ce0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_ce0, grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce0, grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_ce0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_sizes_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_sizes_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bucket_sizes_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bucket_sizes_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_ce0;
        else 
            bucket_sizes_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    bucket_sizes_ce1_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce1, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce1, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_sizes_ce1 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bucket_sizes_ce1 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_ce1;
        else 
            bucket_sizes_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    bucket_sizes_d0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_d0, grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_d0, grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_d0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_d0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_sizes_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_sizes_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bucket_sizes_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bucket_sizes_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_d0;
        else 
            bucket_sizes_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    bucket_sizes_we0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_we0, grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_we0, grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_we0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_we0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_sizes_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_sizes_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bucket_sizes_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_bucket_sizes_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bucket_sizes_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_bucket_sizes_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bucket_sizes_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_bucket_sizes_we0;
        else 
            bucket_sizes_we0 <= ap_const_logic_0;
        end if; 
    end process;


    bucket_we0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            bucket_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_bucket_we0;
        else 
            bucket_we0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_17_fu_126_p1 <= i_fu_52(3 - 1 downto 0);
    grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start <= grp_radix_sort_unified_bucket_1_2_Pipeline_1_fu_68_ap_start_reg;
    grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start <= grp_radix_sort_unified_bucket_1_2_Pipeline_bucket_pointer_initialization_fu_83_ap_start_reg;
    grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_ap_start_reg;
    grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_ap_start_reg;
    grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start <= grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_ap_start_reg;
    i_2_fu_120_p2 <= std_logic_vector(unsigned(i_fu_52) + unsigned(ap_const_lv4_1));
    icmp_ln24_fu_114_p2 <= "1" when (i_fu_52 = ap_const_lv4_8) else "0";
    input_r_address1 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_input_r_address1;
    input_r_ce1 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_input_r_ce1;
    mul_fu_135_p3 <= (empty_17_reg_153 & ap_const_lv2_0);

    sorted_data_address0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_address0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_address0, grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_address0, ap_CS_fsm_state4, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            sorted_data_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            sorted_data_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sorted_data_address0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_address0;
        else 
            sorted_data_address0 <= "XXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    sorted_data_ce0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_ce0, grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_ce0, grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            sorted_data_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            sorted_data_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_input_bucket_fu_89_sorted_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sorted_data_ce0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_ce0;
        else 
            sorted_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    sorted_data_d0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_d0, grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_d0, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            sorted_data_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sorted_data_d0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_d0;
        else 
            sorted_data_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    sorted_data_we0_assign_proc : process(grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_we0, grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_we0, ap_CS_fsm_state4, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            sorted_data_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_output_bucket_fu_99_sorted_data_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            sorted_data_we0 <= grp_radix_sort_unified_bucket_1_2_Pipeline_initialization_fu_74_sorted_data_we0;
        else 
            sorted_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
